// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtifactHealth = { 
/**
 * Path relative to `hermes_home` (POSIX style).
 */
target: string, 
/**
 * sha256 we expected on disk, or `None` if the file is
 * not tracked in our baseline.
 */
expected_sha256: string | null, 
/**
 * sha256 we actually read, or `None` if the file is
 * missing or unreadable.
 */
observed_sha256: string | null, status: ArtifactHealthStatus, };

export type ArtifactHealthStatus = "Current" | "Modified" | "Foreign" | "Missing" | "Error";

/**
 * Per-plugin verification report (TZ §12.3 + ADR-0008).
 *
 * One `HealthReport` per Hermes plugin id. Each `ArtifactHealth`
 * describes one file inside the plugin tree relative to
 * `hermes_home` (e.g. `plugins/agency-agents-router/manifest.yaml`).
 *
 * `expected_sha256` is `None` for files that the operator
 * never deployed through us (e.g. a hand-written `README.md`).
 * `observed_sha256` is `None` when the file is missing on disk.
 */
export type HealthReport = { plugin_id: string, hermes_home: string, artifacts: Array<ArtifactHealth>, 
/**
 * `true` iff every `ArtifactHealth` is `Current` (i.e. the
 * on-disk state matches what we last deployed).
 */
ok: boolean, };

/**
 * Authentication scheme. `Oauth` covers the
 * `native MCP OAuth` case (the Linear manifest) and
 * the `third-party provider` case where the
 * `provider` field names e.g. Google.
 */
export type McpAuth = { "type": "oauth", 
/**
 * None for native MCP OAuth (case 1), Some for
 * third-party providers (case 2).
 */
provider: string | null, };

/**
 * The platform-owned spec for an MCP server manifest.
 * `name` is the manifest directory name; `description`,
 * `source_url`, `transport`, and `auth` map 1:1 to
 * their YAML fields. The manifest adds a static
 * `manifest_version: 1` header.
 */
export type McpServerSpec = { name: string, description: string, source_url: string, transport: McpTransport, auth?: McpAuth | null, };

/**
 * HTTP transport for an MCP server. The 0.19 reference
 * catalog only ships `Http`; `Stdio` lands in 1.3.1.
 */
export type McpTransport = { "type": "http", url: string, };

/**
 * One named check inside a `ProbeReport`. `sha256` is
 * `Some` for file-content checks; `None` for
 * directory-existence checks.
 */
export type ProbeCheck = { name: string, status: ProbeStatus, detail: string, sha256: string | null, };

/**
 * The full structural probe result for a single plugin.
 * `ok` is `true` iff every check is `Ok`.
 */
export type ProbeReport = { plugin_id: string, ok: boolean, checks: Array<ProbeCheck>, };

/**
 * Status of a single check inside a `ProbeReport`.
 */
export type ProbeStatus = "ok" | "missing" | "mismatch" | "error";

export type RuntimeInfo = { version: string, home: string, plugin_dir: string, };
