// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentSummary = { id: string, name: string, version: string, };

export type BackupSummary = { id: string, path: string, created_at: string, };

export type DeploymentSummary = { id: string, system_id: string, status: string, created_at: string, };

export type Finding = { severity: string, rule: string, path: string, reason: string, };

export type LogLine = { ts: string, level: string, target: string, message: string, };

/**
 * Authentication scheme. `Oauth` covers the
 * `native MCP OAuth` case (the Linear manifest) and
 * the `third-party provider` case where the
 * `provider` field names e.g. Google.
 */
export type McpAuth = { "type": "oauth", 
/**
 * None for native MCP OAuth (case 1), Some for
 * third-party providers (case 2).
 */
provider: string | null, };

/**
 * The platform-owned spec for an MCP server manifest.
 * `name` is the manifest directory name; `description`,
 * `source_url`, `transport`, and `auth` map 1:1 to
 * their YAML fields. The manifest adds a static
 * `manifest_version: 1` header.
 */
export type McpServerSpec = { name: string, description: string, source_url: string, transport: McpTransport, auth?: McpAuth | null, };

/**
 * HTTP transport for an MCP server. The 0.19 reference
 * catalog only ships `Http`; `Stdio` lands in 1.3.1.
 */
export type McpTransport = { "type": "http", url: string, };

export type Plan = { system_id: string, operations: Array<PlanOperation>, risk: string, };

export type PlanOperation = { kind: string, target: string, reason: string, };

/**
 * One named check inside a `ProbeReport`. `sha256` is
 * `Some` for file-content checks; `None` for
 * directory-existence checks.
 */
export type ProbeCheck = { name: string, status: ProbeStatus, detail: string, sha256: string | null, };

/**
 * The full structural probe result for a single plugin.
 * `ok` is `true` iff every check is `Ok`.
 */
export type ProbeReport = { plugin_id: string, ok: boolean, checks: Array<ProbeCheck>, };

/**
 * Status of a single check inside a `ProbeReport`.
 */
export type ProbeStatus = "ok" | "missing" | "mismatch" | "error";

export type RuntimeInfo = { version: string, home: string, plugin_dir: string, };

export type ScanResult = { source_id: string, findings: Array<Finding>, };

export type SourceSummary = { id: string, url: string, commit_sha: string, };

export type SystemSummary = { id: string, name: string, version: string, };
