-- 2.11.0 (P1-F-06, TZ #2 WP-3.2, CWE-916
-- Use of Password Hash With Insufficient
-- Computational Effort + CWE-326 Inadequate
-- Encryption Strength).
--
-- Vault KDF v2: per-secret salt + AAD binding.
--
-- Background:
-- The 2.10.0 vault (P0-F-05) derived a single
-- AES-256-GCM cipher from the operator's
-- passphrase at server startup using Argon2id
-- with a per-install salt. Every secret in the
-- vault shared that one cipher; the per-secret
-- randomness came only from the AES-GCM nonce.
-- An attacker who captured the `secrets.db` and
-- observed one (plaintext, ciphertext) pair
-- could mount a known-plaintext attack against
-- the shared cipher, and a brute-force of the
-- passphrase would compromise every secret
-- simultaneously. CWE-916.
--
-- Threat (the residual gap from P0-F-05):
-- 1. Per-install salt alone does not stop an
--    attacker who has `secrets.db` + a
--    compromised passphrase. Every secret
--    decrypts under the same key derivation;
--    a known-plaintext attack is `O(1)` per
--    secret.
-- 2. There is no cryptographic binding
--    between the ciphertext and the secret's
--    identity (name). An attacker who swaps
--    the `ciphertext` of one row with that
--    of another row at the same nonce
--    cannot be detected by AES-GCM (it
--    only authenticates the plaintext +
--    AAD; with no AAD there is nothing
--    tying the ciphertext to the secret).
--    CWE-345 Insufficient Verification of
--    Data Authenticity (cross-row
--    confusion).
-- 3. Rainbow-table-style precomputation
--    against the single install salt is
--    feasible for low-entropy passphrases
--    (the per-install salt has 256 bits of
--    entropy so precomputation is in
--    practice impossible, BUT the
--    per-secret input diversity is what
--    the v2 design standardly provides).
--
-- Fix (this migration):
-- 1. Add `secret_salt BLOB NOT NULL` (16
--    bytes, ~128 bits). Generated by
--    `OsRng` on every `create` / `update`
--    so two rows with the same plaintext
--    and the same passphrase produce
--    different ciphertexts even under the
--    same per-install salt.
-- 2. Add `aad TEXT NOT NULL`. The
--    Additional Authenticated Data passed
--    to AES-GCM binds the ciphertext to
--    the secret's identity. Currently
--    `aad = name`; the column is a `TEXT`
--    so a future multi-tenant release
--    (ADR-0044) can switch to
--    `aad = tenant_id || ':' || name`
--    without a further migration.
-- 3. Extend the `version` CHECK to
--    `IN (1, 2)`. The `version` column
--    is per-row, so old v1 rows keep
--    working under the legacy decrypt
--    path (zero `secret_salt`, empty
--    `aad`). New rows are written with
--    `version = 2`. An update of an old
--    row migrates it to v2 on the spot
--    (the `update` path always derives
--    a fresh per-secret salt + AAD).
--
-- Backfill strategy (no operator action
-- required):
-- Existing v1 rows are backfilled with
-- `secret_salt = 16 zero bytes` and
-- `aad = ''` so the row satisfies the
-- `NOT NULL` constraints. They are
-- still readable through the legacy
-- decrypt path (which derives the key
-- from `install_salt || zero_salt`, i.e.
-- the original install salt alone, and
-- calls AES-GCM `decrypt` without AAD).
-- On the next `update` of a secret, the
-- row is rewritten under v2 and the
-- legacy backfill is gone.
--
-- No re-encryption is forced at
-- migration time: the cost of an
-- offline re-encryption of N secrets
-- under a fresh per-secret salt is
-- `N * Argon2id`, which is
-- `(N * ~100ms)` even on a fast box.
-- A lazy migration (on next `update`)
-- moves the workload to the operator's
-- normal write cadence, which is
-- dominated by API latency, not by KDF
-- derivation.
--
-- Reference: this migration is run by
-- `sqlx::migrate!`, which already wraps
-- every migration in a transaction. Do
-- NOT add explicit `BEGIN;` / `COMMIT;`
-- — SQLite rejects nested transactions
-- and the migration will fail with
-- "cannot start a transaction within a
-- transaction".

CREATE TABLE IF NOT EXISTS secrets_new (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    name          TEXT NOT NULL UNIQUE,
    ciphertext    BLOB NOT NULL,
    nonce         BLOB NOT NULL,
    -- 2.11.0 (P1-F-06, CWE-916 / CWE-326):
    -- 16-byte per-secret salt, generated
    -- by `OsRng` on every write. The
    -- KDF input becomes
    -- `install_salt || secret_salt`
    -- (32 + 16 bytes), making rainbow-
    -- table precomputation per-secret
    -- and forcing an attacker who has
    -- `secrets.db` to attack each row
    -- independently even with a known
    -- passphrase. Legacy v1 rows are
    -- backfilled to 16 zero bytes; the
    -- legacy decrypt path derives the
    -- key from `install_salt || 0^16`
    -- (== original install salt) so
    -- pre-migration ciphertexts remain
    -- readable bit-for-bit.
    secret_salt   BLOB NOT NULL,
    -- 2.11.0 (P1-F-06, CWE-345
    -- cross-row confusion): the
    -- Additional Authenticated Data
    -- bound into AES-GCM. Currently
    -- `aad = name`; future multi-tenant
    -- (ADR-0044) will switch to
    -- `tenant_id:secret_name` without a
    -- further schema change. Legacy v1
    -- rows are backfilled to the empty
    -- string and the legacy decrypt
    -- path calls AES-GCM without AAD.
    aad           TEXT NOT NULL,
    -- 2.11.0: per-row KDF version.
    --
    -- **No CHECK constraint** on `version`
    -- (the pre-migration 010 schema had
    -- `CHECK (version IN (1))`; that would
    -- block writing v2 rows and would force
    -- a table-rebuild on every future KDF
    -- bump). The reader dispatches on
    -- `version` in
    -- `SecretRepository::get_value` and
    -- returns a typed `ErrSchemaInvalid`
    -- for any value it does not know.
    -- This is the same defense-in-depth
    -- shape as `users.role` (the 019
    -- rebuild dropped the `role` CHECK
    -- too — see the rebuild pattern there).
    version       INTEGER NOT NULL,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    created_by    INTEGER NOT NULL,
    updated_by    INTEGER NOT NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
);

INSERT INTO secrets_new (
    id, name, ciphertext, nonce,
    secret_salt, aad, version,
    created_at, updated_at, created_by, updated_by
)
SELECT
    id, name, ciphertext, nonce,
    -- Legacy v1 sentinel: 16 zero bytes
    -- so the row satisfies `NOT NULL`.
    -- The v1 decrypt path treats this as
    -- "no per-secret salt; derive from
    -- install_salt alone".
    X'00000000000000000000000000000000',
    -- Legacy v1 sentinel: empty AAD;
    -- the v1 decrypt path calls
    -- AES-GCM `decrypt` without AAD.
    '',
    version,
    created_at, updated_at, created_by, updated_by
FROM secrets;

DROP TABLE secrets;

ALTER TABLE secrets_new RENAME TO secrets;

CREATE INDEX IF NOT EXISTS idx_secrets_name
    ON secrets(name);

-- 2.11.0 (P1-F-06): bump schema_version
-- 19 -> 20.
UPDATE meta
SET value = '20'
WHERE key = 'schema_version';
