//! HTTP integration tests for `agency-server` (2.0.0).
//!
//! Each test binds a real `axum` router to
//! `127.0.0.1:0` (the kernel picks a free port), then
//! drives the API with `reqwest`. The tests use the
//! `router(state)` constructor so they can inject a
//! hermetic SQLite DB and a known bearer token — no
//! filesystem state outside the tempdir.

use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::Arc;

use agent_dep_core::infrastructure::repository::audit_log_repository::{
    AuditLogRepository, AuditOutcome,
};
use agent_dep_core::infrastructure::repository::pending_deploys_repository::PendingDeployRepository;
use agent_dep_core::infrastructure::repository::secrets_repository::SecretRepository;
use agent_dep_core::infrastructure::repository::targets_repository::TargetRepository;
use agent_dep_core::infrastructure::repository::users_repository::{Role, UserRepository};
use agent_dep_core::infrastructure::sqlite::connect;
use agent_dep_server::audit_recorder::AuditRecorder;
use agent_dep_server::{router, ServerState};
use serde_json::json;
use tokio::net::TcpListener;

struct TestServer {
    base: String,
    /// The 2.1.0 server always boots with a single
    /// `admin` user (or migrates a 2.0.0 legacy token
    /// to one). Tests use the admin token for setup
    /// and create additional users for role checks.
    admin_token: String,
    /// 2.5.3 (ADR-0033 follow-up): shared
    /// `TargetRepository` for `_ensure_target`.
    /// We share the same pool as the server so
    /// INSERTs in the test are visible to the
    /// running router without a WAL-visibility
    /// race across two pools.
    targets: std::sync::Arc<TargetRepository>,
    _dir: tempfile::TempDir,
}

async fn boot() -> TestServer {
    // 2.11.0 (B1, audit): the test
    // harness enables the
    // AGENCY_BEARER_FALLBACK env
    // var so the existing
    // test infrastructure (which
    // uses the pre-OIDC admin
    // token) keeps working. The
    // dedicated CSRF / B1 tests
    // unset the var locally to
    // exercise the WARN-AND-REJECT
    // path. Tests run single-
    // threaded (--test-threads=1)
    // so the env mutation is
    // safe.
    // SAFETY: set_var is marked
    // unsafe because of libc
    // thread-safety, but the
    // http_integration suite is
    // single-threaded.
    unsafe {
        std::env::set_var("AGENCY_BEARER_FALLBACK", "1");
    }
    boot_with_legacy(None).await
}

async fn boot_with_legacy(legacy: Option<&str>) -> TestServer {
    let dir = tempfile::tempdir().expect("tempdir");
    let db_path: PathBuf = dir.path().join("audit.db");
    let db = connect(&db_path).await.expect("connect");
    db.migrate().await.expect("migrate");
    let audit = AuditRecorder::direct(AuditLogRepository::new(db.pool().clone()));
    let users = UserRepository::new(db.pool().clone());
    let admin_token = match legacy {
        Some(t) => {
            // 2.0.0 → 2.1.0 migration path: the legacy
            // token becomes the admin's token. The
            // state holds a hint but the users table
            // is the source of truth.
            users.migrate_legacy_token(t).await.expect("migrate legacy");
            t.to_string()
        }
        None => {
            let created = users
                .create("admin", Role::Admin)
                .await
                .expect("create admin");
            created.token
        }
    };
    let deploys = PendingDeployRepository::new(db.pool().clone());
    // P0-F-05 (TZ #1 §6 F-05 + TZ #2 WP-2.1):
    // the test vault now takes the per-install
    // salt. Tests use a deterministic all-zero
    // salt so failures are reproducible across
    // runs; the production salt is generated by
    // vault_init::load_or_generate_install_salt.
    let test_install_salt =
        [0u8; agent_dep_core::infrastructure::repository::secrets_repository::INSTALL_SALT_LEN];
    let secrets = SecretRepository::new(db.pool().clone(), "test-passphrase", &test_install_salt)
        .expect("vault");
    // 2.5.3: build one `TargetRepository`
    // and share it between `state` (consumed
    // by `router`) and `TestServer` (used by
    // `_ensure_target`). Two separate
    // `TargetRepository` instances over the
    // same `SqlitePool` can race on WAL
    // visibility in some Windows configs,
    // which is what bit us at first.
    let targets_repo = TargetRepository::new(db.pool().clone());
    let oidc = agent_dep_server::oidc::OidcConfig::default();
    let oidc_pending = std::sync::Arc::new(
        agent_dep_core::infrastructure::repository::oidc_pending_repository::OidcPendingRepository::new(
            db.pool().clone(),
        ),
    );
    let oidc_client: Arc<dyn agent_dep_server::oidc_client::OidcClient> =
        Arc::new(agent_dep_server::oidc_client::MockOidcClient);
    let state = ServerState {
        db: db.clone(),
        audit,
        users,
        deploys,
        secrets,
        targets: targets_repo.clone(),
        oidc,
        oidc_pending,
        oidc_client,
        legacy_token: Arc::new(legacy.map(|s| s.to_string())),
        // 2.11.0 (P1-F-03a/b, CWE-613):
        // session store + cookie
        // security flag. Plain HTTP
        // tests use `cookie_secure =
        // false` so the cookie is
        // accepted on the
        // `http://127.0.0.1:...`
        // listener.
        sessions:
            agent_dep_core::infrastructure::repository::sessions_repository::SessionRepository::new(
                db.pool().clone(),
            ),
        cookie_secure: false,
        // 2.11.0 (P1-D-03, CWE-362):
        // Idempotency-Key cache. The
        // middleware is a no-op for
        // requests without the
        // `Idempotency-Key` header,
        // so the existing tests work
        // unchanged. A future
        // P1-D-03 test will exercise
        // the replay path.
        idempotency:
            agent_dep_core::infrastructure::repository::idempotency_repository::IdempotencyRepository::new(
                db.pool().clone(),
            ),
        // 2.11.0 (P1-RL-01, P1-API-03): the
        // rate limiter + body / header
        // limits. The integration tests
        // use the defaults (100 req/s
        // burst 200, 1 MiB body, 100
        // headers); a future
        // rate-limit test will swap in
        // a `with_capacity_and_rate`
        // builder.
        rate_limiter: Arc::new(agent_dep_server::rate_limit::RateLimiter::new()),
        max_body_bytes: Arc::new(std::sync::atomic::AtomicU32::new(
            agent_dep_server::rate_limit::MAX_BODY_BYTES,
        )),
        max_header_count: Arc::new(std::sync::atomic::AtomicU32::new(
            agent_dep_server::rate_limit::MAX_HEADER_COUNT,
        )),
    };
    let app = router(state);
    let listener = TcpListener::bind("127.0.0.1:0").await.expect("bind");
    let addr: SocketAddr = listener.local_addr().expect("local_addr");
    let base = format!("http://{addr}");
    tokio::spawn(async move {
        let _ = axum::serve(listener, app).await;
    });
    tokio::time::sleep(std::time::Duration::from_millis(50)).await;
    TestServer {
        base,
        admin_token,
        targets: std::sync::Arc::new(targets_repo),
        _dir: dir,
    }
}

#[tokio::test]
async fn health_is_open_and_returns_ok() {
    let srv = boot().await;
    let resp = reqwest::get(format!("{}/v1/health", srv.base))
        .await
        .expect("get");
    assert_eq!(resp.status(), 200);
    let body: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(body["status"], "ok");
}

#[tokio::test]
async fn audit_requires_bearer_token() {
    let srv = boot().await;
    let resp = reqwest::get(format!("{}/v1/audit", srv.base))
        .await
        .expect("get");
    assert_eq!(resp.status(), 401);
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/audit", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("send");
    assert_eq!(resp.status(), 200);
}

#[tokio::test]
async fn audit_list_records_each_request() {
    let srv = boot().await;
    // Two failed auths (one missing, one bad).
    let _ = reqwest::get(format!("{}/v1/audit", srv.base)).await;
    let _ = reqwest::Client::new()
        .get(format!("{}/v1/audit", srv.base))
        .bearer_auth("wrong-token")
        .send()
        .await;
    // One successful call.
    let _ = reqwest::Client::new()
        .get(format!("{}/v1/audit?limit=10", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("send");

    // 2.11.0 (P1-PERF-01): the GET audit
    // calls now go through the
    // debounced `record_async` path;
    // wait for the spawned tasks to
    // commit before asserting on the
    // list. 100 ms is well over the
    // SQLite WAL commit time.
    tokio::time::sleep(std::time::Duration::from_millis(100)).await;

    let resp = reqwest::Client::new()
        .get(format!("{}/v1/audit?limit=50", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("send");
    assert_eq!(resp.status(), 200);
    let body: serde_json::Value = resp.json().await.expect("json");
    let items = body["items"].as_array().expect("items array");
    assert!(
        items.len() >= 3,
        "expected ≥ 3 audit rows (2 errors + 1 ok), got {}",
        items.len()
    );
    // Oldest first; the first two are the unauth attempts.
    assert_eq!(items[0]["outcome"], "error");
    assert_eq!(items[1]["outcome"], "error");
    assert_eq!(items[2]["outcome"], "ok");
    assert_eq!(items[0]["actor"], "anonymous");
    assert_eq!(items[2]["actor"], "admin");
}

#[tokio::test]
async fn systems_list_is_empty_for_fresh_db() {
    let srv = boot().await;
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/systems", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("send");
    assert_eq!(resp.status(), 200);
    let body: serde_json::Value = resp.json().await.expect("json");
    let arr = body.as_array().expect("array");
    assert!(arr.is_empty(), "fresh DB has no active snapshots");
}

#[tokio::test]
async fn plan_endpoint_returns_writes_for_a_real_catalog() {
    use agent_dep_core::infrastructure::repository::audit_log_repository::AuditLogRepository;
    let dir = tempfile::tempdir().unwrap();
    let cat = dir.path().join("catalog");
    std::fs::create_dir_all(cat.join("agents/engineering")).unwrap();
    std::fs::write(
        cat.join("divisions.json"),
        r#"{"divisions":[{"id": "engineering", "label": "Eng", "order": 0}]}"#,
    )
    .unwrap();
    let be_md = r#"---
id: be
name: Backend
display_name: Backend
division: engineering
role: backend
description: be
version: 1.0.0
sensitive: false
activation_phrases: []
tools: []
---

You are be.
"#;
    std::fs::write(cat.join("agents/engineering/be.md"), be_md).unwrap();
    let sys = r#"apiVersion: agent-dep/v1
kind: System
metadata:
  id: test-sys
  name: test
spec:
  source: ./catalog
  runtime_type: hermes
  agents:
    - ref: be@1.0.0
"#;
    let db_path = dir.path().join("audit.db");
    let db = connect(&db_path).await.unwrap();
    db.migrate().await.unwrap();
    let audit = AuditRecorder::direct(AuditLogRepository::new(db.pool().clone()));
    let users = UserRepository::new(db.pool().clone());
    let created = users
        .create(
            "admin",
            agent_dep_core::infrastructure::repository::users_repository::Role::Admin,
        )
        .await
        .unwrap();
    let token = created.token.clone();
    let deploys = PendingDeployRepository::new(db.pool().clone());
    // P0-F-05 (TZ #1 §6 F-05 + TZ #2 WP-2.1):
    // the test vault now takes the per-install
    // salt. Tests use a deterministic all-zero
    // salt so failures are reproducible across
    // runs; the production salt is generated by
    // vault_init::load_or_generate_install_salt.
    let test_install_salt =
        [0u8; agent_dep_core::infrastructure::repository::secrets_repository::INSTALL_SALT_LEN];
    let secrets = SecretRepository::new(db.pool().clone(), "test-passphrase", &test_install_salt)
        .expect("vault");
    let targets = TargetRepository::new(db.pool().clone());
    let oidc = agent_dep_server::oidc::OidcConfig::default();
    let oidc_pending = std::sync::Arc::new(
        agent_dep_core::infrastructure::repository::oidc_pending_repository::OidcPendingRepository::new(
            db.pool().clone(),
        ),
    );
    let oidc_client: Arc<dyn agent_dep_server::oidc_client::OidcClient> =
        Arc::new(agent_dep_server::oidc_client::MockOidcClient);
    // 2.11.0 (P1-F-03b, CWE-613):
    // server-side session store.
    // Must be built BEFORE `db` is
    // moved into `ServerState` (the
    // `SessionRepository` takes a
    // `SqlitePool`, and `db` is
    // moved on the next line).
    let sessions =
        agent_dep_core::infrastructure::repository::sessions_repository::SessionRepository::new(
            db.pool().clone(),
        );
    // 2.11.0 (P1-D-03, CWE-362):
    // Idempotency-Key cache. Built
    // BEFORE `db` is moved into
    // `ServerState` (the
    // `IdempotencyRepository` takes
    // a `SqlitePool`, and `db` is
    // moved on the next line).
    let idempotency_for_state =
        agent_dep_core::infrastructure::repository::idempotency_repository::IdempotencyRepository::new(
            db.pool().clone(),
        );
    let state = ServerState {
        db,
        audit,
        users,
        deploys,
        secrets,
        targets,
        oidc,
        oidc_pending,
        oidc_client,
        legacy_token: Arc::new(Some(token.clone())),
        sessions,
        cookie_secure: false,
        // 2.11.0 (P1-D-03, CWE-362):
        // Idempotency-Key cache. See
        // the first `ServerState`
        // construction above for
        // the full rationale; the
        // same `IdempotencyRepository`
        // is built here.
        idempotency: idempotency_for_state,
        // 2.11.0 (P1-RL-01, P1-API-03): see
        // the first ServerState
        // construction in this file
        // for the rationale; this
        // second construction is the
        // path for the `registered_admin`
        // fixture used by the
        // admin-level integration
        // tests.
        rate_limiter: Arc::new(agent_dep_server::rate_limit::RateLimiter::new()),
        max_body_bytes: Arc::new(std::sync::atomic::AtomicU32::new(
            agent_dep_server::rate_limit::MAX_BODY_BYTES,
        )),
        max_header_count: Arc::new(std::sync::atomic::AtomicU32::new(
            agent_dep_server::rate_limit::MAX_HEADER_COUNT,
        )),
    };
    let app = router(state);
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let addr = listener.local_addr().unwrap();
    let base = format!("http://{addr}");
    tokio::spawn(async move {
        let _ = axum::serve(listener, app).await;
    });
    tokio::time::sleep(std::time::Duration::from_millis(50)).await;

    let body = json!({
        // P0-F-07: the request now carries
        // the pre-registered `source_id`
        // (UUID) instead of a caller-
        // supplied filesystem path. The
        // helper `register_local_source`
        // inserts a row into the `sources`
        // table so `compute_plan_from_source`
        // can resolve the path.
        "source_id": register_local_source(
            &db_path,
            &cat,
        )
        .await,
        "system_yaml": sys,
    });
    let resp = reqwest::Client::new()
        .post(format!("{base}/v1/systems/plan"))
        .bearer_auth(&token)
        .json(&body)
        .send()
        .await
        .expect("post");
    let status = resp.status();
    let body_text = resp.text().await.unwrap_or_default();
    assert_eq!(
        status, 200,
        "plan should succeed: status={status} body={body_text}"
    );
    let v: serde_json::Value = serde_json::from_str(&body_text).expect("json");
    assert_eq!(v["system_id"], "test-sys");
    let writes = v["writes"].as_array().expect("writes");
    assert_eq!(writes.len(), 1);
    assert_eq!(writes[0]["agent_ref"], "be@1.0.0");
}

// P0-F-07: an unregistered / unknown
// `source_id` is rejected by the server
// (it does not exist in the `sources`
// table). The old test sent a bogus
// filesystem path; post-fix we send a
// bogus UUID and `compute_plan_from_source`
// returns `Err(SourceNotRegistered)`.
// The post-fix error mapping (via
// `error_response::from_any_error`)
// surfaces it as a 4xx with a typed
// `ErrorResponse { code, kind, hint }`.
// The hardening is real — the caller
// can no longer pass a caller-supplied
// filesystem path; the server resolves
// the path from the pre-registered
// `sources` table. The happy-path
// test `plan_endpoint_returns_writes_for_a_real_catalog`
// is the executable spec for the fix.
#[tokio::test]
async fn plan_endpoint_reports_bad_catalog_as_400() {
    let srv = boot().await;
    // P0-F-07: a bogus UUID (no row
    // in `sources`) must be rejected
    // with a 4xx + stable error code.
    // The pre-fix behavior accepted
    // any caller-supplied path, which
    // is a path-traversal vector
    // (CWE-22). Post-fix the server
    // refuses unknown `source_id`s.
    let body = json!({
        "source_id": "00000000-0000-0000-0000-000000000000",
        "system_yaml": "id: x\n",
    });
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/systems/plan", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&body)
        .send()
        .await
        .expect("post");
    let status = resp.status();
    assert_eq!(
        status, 400,
        "P0-F-07: unregistered source_id should be 400 (bad request). \
         Got status={status}"
    );
    // P0-API-04: the response is a typed
    // `ErrorResponse { code, kind, hint }`.
    // The pre-fix `error` field (a free-form
    // string with the CoreError's
    // `to_string()`) is gone — it used to
    // leak internal path/error messages.
    // The post-fix `code` is a stable,
    // machine-readable identifier.
    let v: serde_json::Value = resp.json().await.expect("json");
    assert!(
        v["code"].is_string(),
        "P0-API-04: response must include a string `code` field; got: {v}"
    );
    let code = v["code"].as_str().unwrap();
    assert!(
        code == "schema.invalid" || code == "internal.io" || code == "internal.untyped",
        "expected one of the stable error codes; got `{code}`"
    );
    let hint = v["hint"].as_str().unwrap_or("");
    assert!(
        !hint.contains("not a directory"),
        "P0-API-04: hint MUST NOT echo internal error messages; got: {hint}"
    );
}

// Suppress unused-import warning for `AuditOutcome`; the
// tests above import the symbol through re-exports.
#[allow(dead_code)]
fn _outcome_marker() -> AuditOutcome {
    AuditOutcome::Ok
}

// ---------------------------------------------------------------------------
// 2.1.0 — RBAC integration tests (ADR-0019).
// ---------------------------------------------------------------------------

async fn create_user(srv: &TestServer, name: &str, role: Role) -> String {
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/users", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({ "name": name, "role": role }))
        .send()
        .await
        .expect("create user");
    assert_eq!(resp.status(), 201, "create user: {:?}", resp);
    let v: serde_json::Value = resp.json().await.expect("json");
    v["token"].as_str().expect("token").to_string()
}

#[tokio::test]
async fn viewer_cannot_trigger_plan() {
    let srv = boot().await;
    let viewer_token = create_user(&srv, "vw", Role::Viewer).await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/systems/plan", srv.base))
        .bearer_auth(&viewer_token)
        .json(&json!({ "catalog": "Z:/x", "system_yaml": "id: y" }))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 403, "viewer must be forbidden");
    let v: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(v["error"], "forbidden");
}

#[tokio::test]
async fn operator_can_read_audit() {
    let srv = boot().await;
    let op_token = create_user(&srv, "op", Role::Operator).await;
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/audit?limit=10", srv.base))
        .bearer_auth(&op_token)
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 200, "operator must read the audit log");
    // 2.11.0 (P1-PERF-01): the audit
    // entry for the `list_audit`
    // call above is enqueued via
    // `record_async`; wait for it
    // to commit before reading.
    tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    let resp2 = reqwest::Client::new()
        .get(format!("{}/v1/audit?limit=10", srv.base))
        .bearer_auth(&op_token)
        .send()
        .await
        .expect("get");
    let v: serde_json::Value = resp2.json().await.expect("json");
    let items = v["items"].as_array().expect("items");
    assert!(!items.is_empty(), "audit log should have at least one row");
}

#[tokio::test]
async fn admin_can_create_user() {
    let srv = boot().await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/users", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({ "name": "newby", "role": "operator" }))
        .send()
        .await
        .expect("create");
    assert_eq!(resp.status(), 201);
    let v: serde_json::Value = resp.json().await.expect("json");
    let token = v["token"].as_str().expect("token");
    assert!(!token.is_empty());
    assert_eq!(v["name"], "newby");
    assert_eq!(v["role"], "operator");

    // The new user's token works.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/systems", srv.base))
        .bearer_auth(token)
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 200);
}

#[tokio::test]
async fn legacy_token_migrates_to_admin_on_first_start() {
    let legacy = "a-very-specific-2.0.0-token";
    let srv = boot_with_legacy(Some(legacy)).await;
    // The legacy token must log in as admin.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/audit", srv.base))
        .bearer_auth(legacy)
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 200, "legacy token must keep working");
    // A second GET will see the first GET's audit row
    // (we await the audit write before responding,
    // but the response is read before the second
    // request's row is added — so we make a third
    // call to confirm the admin attribution).
    let _ = reqwest::Client::new()
        .get(format!("{}/v1/audit", srv.base))
        .bearer_auth(legacy)
        .send()
        .await
        .expect("get");
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/audit", srv.base))
        .bearer_auth(legacy)
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 200);
    let v: serde_json::Value = resp.json().await.expect("json");
    let items = v["items"].as_array().expect("items");
    let ok_row = items
        .iter()
        .find(|r| r["outcome"] == "ok")
        .expect("at least one ok row");
    assert_eq!(
        ok_row["actor"], "admin",
        "legacy token's bearer must attribute rows to `admin`"
    );
}

// ---------------------------------------------------------------------------
// 2.2.0 — approvals workflow integration tests (ADR-0020).
// ---------------------------------------------------------------------------

const APPROVALS_SYS: &str = "apiVersion: agent-dep/v1
kind: System
metadata:
  id: approval-sys
  name: approval
spec:
  source: ./catalog
  runtime_type: hermes
  agents:
    - ref: be@1.0.0
";

fn _write_approvals_catalog(cat: &std::path::Path) {
    std::fs::create_dir_all(cat.join("agents").join("engineering")).unwrap();
    std::fs::write(
        cat.join("divisions.json"),
        r#"{"divisions":[{"id":"engineering","label":"Eng","order":0}]}"#,
    )
    .unwrap();
    let be_md = "---
id: be
name: Backend
division: engineering
role: backend
description: be
version: 1.0.0
sensitive: false
activation_phrases: []
tools: []
---

You are be.
";
    std::fs::write(cat.join("agents").join("engineering").join("be.md"), be_md).unwrap();
}

/// 2.5.3 (ADR-0033 follow-up) helper:
/// create a `Target` row via the
/// server's `POST /v1/targets` endpoint
/// using the admin token. This goes
/// through `state.targets` directly,
/// so a subsequent `state.targets.
/// find_by_env_name` inside
/// `request_deploy` MUST see it
/// (same `state`, same pool).
/// Idempotent: a 201 is success, a
/// 4xx is fine if the target was
/// already created in this boot —
/// we look the id up via the shared
/// `targets_repo` afterwards.
async fn _ensure_target(srv: &TestServer, environment: &str, name: &str) -> i64 {
    let body = json!({
        "name": name,
        "environment": environment,
        "path": "/srv/hermes",
        "path_kind": "posix",
    });
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/targets", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&body)
        .send()
        .await
        .expect("post target");
    let status = resp.status();
    let resp_body = resp.text().await.expect("target body");
    if status.is_success() {
        let v: serde_json::Value = serde_json::from_str(&resp_body).expect("json");
        return v["id"].as_i64().expect("target id");
    }
    // 4xx — likely a duplicate from an
    // earlier test in this boot. Look
    // the row up via the shared repo.
    use agent_dep_core::infrastructure::repository::pending_deploys_repository::Environment;
    let env = Environment::parse(environment).expect("env parse");
    let existing = srv
        .targets
        .find_by_env_name(env, name)
        .await
        .expect("find target");
    existing.unwrap_or_else(|| {
        panic!(
            "POST /v1/targets failed (status={status} body={resp_body}) and target is not visible afterwards"
        )
    }).id
}

async fn _request_deploy(srv: &TestServer, token: &str) -> (i64, serde_json::Value) {
    // The catalog lives next to the test binary's
    // own tempdir; we use a fresh subdir so the test
    // is hermetic.
    let cat = srv._dir.path().join("approvals_catalog");
    std::fs::create_dir_all(&cat).unwrap();
    _write_approvals_catalog(&cat);
    // 2.5.3 (ADR-0033 follow-up):
    // every `POST /v1/deploys` MUST
    // declare a `target`. We create
    // a hermetic target for this
    // test.
    let _ = _ensure_target(srv, "dev", "approval-target").await;
    // P0-F-07: the request must carry
    // a real `source_id` (UUID) that
    // resolves to a row in the
    // `sources` table. Register one
    // pointing at the hermetic catalog.
    let source_id = register_local_source(&srv._dir.path().join("audit.db"), &cat).await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/deploys", srv.base))
        .bearer_auth(token)
        .json(&json!({
            "source_id": source_id,
            "system_yaml": APPROVALS_SYS,
            "environment": "dev",
            "target": "approval-target",
        }))
        .send()
        .await
        .expect("post deploy");
    let status = resp.status();
    let body = resp.text().await.expect("body");
    assert_eq!(
        status, 201,
        "request deploy: status={} body={}",
        status, body
    );
    let v: serde_json::Value = serde_json::from_str(&body).expect("json");
    (v["deploy"]["id"].as_i64().expect("id"), v)
}

#[tokio::test]
async fn operator_creates_pending_deploy() {
    let srv = boot().await;
    let op_token = create_user(&srv, "op", Role::Operator).await;
    let (id, _) = _request_deploy(&srv, &op_token).await;
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/deploys/{id}", srv.base))
        .bearer_auth(&op_token)
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 200);
    let v: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(v["status"], "pending");
}

#[tokio::test]
async fn viewer_reads_deploys() {
    let srv = boot().await;
    let op_token = create_user(&srv, "op", Role::Operator).await;
    let vw_token = create_user(&srv, "vw", Role::Viewer).await;
    let _ = _request_deploy(&srv, &op_token).await;
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/deploys", srv.base))
        .bearer_auth(&vw_token)
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 200);
    let v: serde_json::Value = resp.json().await.expect("json");
    let arr = v.as_array().expect("array");
    assert_eq!(arr.len(), 1);
    assert_eq!(arr[0]["status"], "pending");
}

#[tokio::test]
async fn admin_approves_pending_deploy() {
    let srv = boot().await;
    let op_token = create_user(&srv, "op", Role::Operator).await;
    let (id, _) = _request_deploy(&srv, &op_token).await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/deploys/{id}/approve", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("approve");
    assert_eq!(resp.status(), 200);
    let v: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(v["status"], "approved");
    assert!(v["approved_by"].is_i64());
    // 2.10.0 (P1-AUD-FIX, CWE-778):
    // approve Ok branch now uses
    // `record_sync` (P1-PERF-01
    // over-conversion fix). The
    // audit row is durable before
    // the 200 returns, so no sleep
    // is needed before the read.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/audit?limit=200", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("get");
    let v: serde_json::Value = resp.json().await.expect("json");
    let items = v["items"].as_array().expect("items");
    let approve_row = items
        .iter()
        .find(|r| r["action"] == "POST /v1/deploys/:id/approve")
        .unwrap_or_else(|| {
            panic!(
                "no approve audit row found; got actions: {:?}",
                items
                    .iter()
                    .map(|r| r["action"].as_str().unwrap_or("?"))
                    .collect::<Vec<_>>()
            )
        });
    assert_eq!(approve_row["outcome"], "ok");
    assert_eq!(approve_row["actor"], "admin");
}

#[tokio::test]
async fn admin_rejects_pending_deploy() {
    let srv = boot().await;
    let op_token = create_user(&srv, "op", Role::Operator).await;
    let (id, _) = _request_deploy(&srv, &op_token).await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/deploys/{id}/reject", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({ "reason": "policy blocked" }))
        .send()
        .await
        .expect("reject");
    assert_eq!(resp.status(), 200);
    let v: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(v["status"], "rejected");
    assert_eq!(v["rejection_reason"], "policy blocked");
}

// ---------------------------------------------------------------------------
// 2.3.0 — vault integration tests (ADR-0021).
// ---------------------------------------------------------------------------

#[tokio::test]
async fn admin_creates_secret_201() {
    let srv = boot().await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/secrets", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({ "name": "hermes-api-token", "value": "secret-XYZ" }))
        .send()
        .await
        .expect("create");
    assert_eq!(resp.status(), 201, "create secret: {:?}", resp);
    let v: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(v["name"], "hermes-api-token");
    // The list view does NOT carry a value field.
    assert!(v.get("value").is_none());
}

#[tokio::test]
async fn viewer_lists_secrets_without_values() {
    let srv = boot().await;
    // Seed a secret as admin.
    let _ = reqwest::Client::new()
        .post(format!("{}/v1/secrets", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({ "name": "k1", "value": "v1" }))
        .send()
        .await
        .expect("seed k1");
    // Operator-level token for the read.
    let op_token = create_user(&srv, "op", Role::Operator).await;
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/secrets", srv.base))
        .bearer_auth(&op_token)
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 200);
    let v: serde_json::Value = resp.json().await.expect("json");
    let arr = v.as_array().expect("array");
    assert_eq!(arr.len(), 1);
    assert_eq!(arr[0]["name"], "k1");
    assert!(
        arr[0].get("value").is_none(),
        "list must never include value"
    );
}

#[tokio::test]
async fn operator_reads_secret_value_200() {
    // 2.10.0 (B3, audit CWE-598):
    // GET /v1/secrets/:name is GONE
    // (returns 410 Gone with a
    // migration pointer). The
    // reveal path is
    // POST /v1/secrets/:name/reveal
    // and requires Admin role +
    // mandatory `reason` body field.
    // Operator role is rejected at
    // the middleware layer.
    let srv = boot().await;
    let _ = reqwest::Client::new()
        .post(format!("{}/v1/secrets", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({ "name": "k", "value": "the-value" }))
        .send()
        .await
        .expect("seed");
    let op_token = create_user(&srv, "op", Role::Operator).await;
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/secrets/k", srv.base))
        .bearer_auth(&op_token)
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 410, "GET must be GONE in 2.10.0");
    // POST /reveal with Operator role
    // — middleware-layer rejection
    // (403), not even reaching the
    // handler.
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/secrets/k/reveal", srv.base))
        .bearer_auth(&op_token)
        .json(&json!({ "reason": "operator probing" }))
        .send()
        .await
        .expect("post reveal");
    assert_eq!(resp.status(), 403, "Operator must NOT be allowed to reveal");
}

#[tokio::test]
async fn admin_reveals_secret_value_200_with_no_cache_headers() {
    // 2.10.0 (B3, audit CWE-598)
    // happy path: Admin role +
    // mandatory `reason` returns
    // the value with
    // `Cache-Control: no-store, no-cache, must-revalidate`
    // + `Pragma: no-cache` headers.
    let srv = boot().await;
    let _ = reqwest::Client::new()
        .post(format!("{}/v1/secrets", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({ "name": "k", "value": "the-value" }))
        .send()
        .await
        .expect("seed");
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/secrets/k/reveal", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({ "reason": "investigating a deploy failure" }))
        .send()
        .await
        .expect("reveal");
    assert_eq!(resp.status(), 200);
    // The no-cache headers MUST be
    // present so HTTP caches and the
    // browser back-button do not
    // retain the plaintext. Read
    // headers BEFORE consuming
    // `resp` with `.json()`.
    let headers = resp.headers();
    let cache_control = headers
        .get(axum::http::header::CACHE_CONTROL)
        .expect("Cache-Control header")
        .to_str()
        .expect("ascii");
    assert!(
        cache_control.contains("no-store")
            && cache_control.contains("no-cache")
            && cache_control.contains("must-revalidate"),
        "Cache-Control must include no-store + no-cache + must-revalidate, got: {cache_control}"
    );
    assert_eq!(
        headers
            .get(axum::http::header::PRAGMA)
            .expect("Pragma header")
            .to_str()
            .expect("ascii"),
        "no-cache"
    );
    // The plaintext value is in the
    // body.
    let v: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(v["name"], "k");
    assert_eq!(v["value"], "the-value");
    // 2.11.0 (P1-PERF-01): GET audit
    // is debounced; sleep briefly so
    // the reveal row is visible.
    tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/audit?limit=50", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("get audit");
    let v: serde_json::Value = resp.json().await.expect("json");
    let items = v["items"].as_array().expect("items");
    let reveal_row = items
        .iter()
        .find(|r| r["action"] == "POST /v1/secrets/:name/reveal" && r["outcome"] == "ok")
        .expect("reveal row must be in audit log");
    let details: serde_json::Value =
        serde_json::from_str(reveal_row["details"].as_str().unwrap_or("{}")).expect("details json");
    assert_eq!(
        details["reason"].as_str(),
        Some("investigating a deploy failure"),
        "audit row must include the operator-supplied reason"
    );
}

#[tokio::test]
async fn reveal_secret_without_reason_returns_400() {
    // 2.10.0 (B3): the `reason` field
    // is mandatory. A blank / missing
    // reason means the audit row
    // would have no human-readable
    // answer to "why was this pulled",
    // so we reject the request and
    // audit the rejection.
    let srv = boot().await;
    let _ = reqwest::Client::new()
        .post(format!("{}/v1/secrets", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({ "name": "k", "value": "v" }))
        .send()
        .await
        .expect("seed");
    // Whitespace-only reason is
    // rejected (it would be useless
    // in the audit row).
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/secrets/k/reveal", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({ "reason": "   " }))
        .send()
        .await
        .expect("reveal empty reason");
    assert_eq!(resp.status(), 400);
    let v: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(v["code"], "schema.invalid");
    // Audit row records the rejection
    // (so a stuck / scripted client
    // surfaces in the log).
    tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/audit?limit=50", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("get audit");
    let v: serde_json::Value = resp.json().await.expect("json");
    let items = v["items"].as_array().expect("items");
    let reject_row = items
        .iter()
        .find(|r| r["action"] == "POST /v1/secrets/:name/reveal" && r["outcome"] == "error")
        .expect("rejection row must be in audit log");
    let details: serde_json::Value =
        serde_json::from_str(reject_row["details"].as_str().unwrap_or("{}")).expect("details json");
    assert_eq!(
        details["reason"].as_str(),
        Some("missing reason in request body")
    );
}

#[tokio::test]
async fn admin_deletes_secret_204_and_audit_logs_access() {
    let srv = boot().await;
    let _ = reqwest::Client::new()
        .post(format!("{}/v1/secrets", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({ "name": "k", "value": "v" }))
        .send()
        .await
        .expect("seed");
    let resp = reqwest::Client::new()
        .delete(format!("{}/v1/secrets/k", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("delete");
    assert_eq!(resp.status(), 204);
    // After delete, reveal returns 404
    // (the secret is gone). 2.10.0
    // (B3, audit CWE-598) replaced
    // GET /v1/secrets/:name with
    // POST /v1/secrets/:name/reveal.
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/secrets/k/reveal", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({ "reason": "post-delete sanity check" }))
        .send()
        .await
        .expect("reveal after delete");
    assert_eq!(resp.status(), 404);
    // The audit log records every
    // step: create, delete, then the
    // failed reveal. 2.11.0 (P1-PERF-01):
    // GET audit is debounced; the
    // list_audit call itself is
    // async, so we wait briefly for
    // the drain.
    tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/audit?limit=200", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("get audit");
    let v: serde_json::Value = resp.json().await.expect("json");
    let items = v["items"].as_array().expect("items");
    let has_create = items
        .iter()
        .any(|r| r["action"] == "POST /v1/secrets" && r["outcome"] == "ok");
    let has_delete = items
        .iter()
        .any(|r| r["action"] == "DELETE /v1/secrets/:name" && r["outcome"] == "ok");
    let has_failed_reveal = items
        .iter()
        .any(|r| r["action"] == "POST /v1/secrets/:name/reveal" && r["outcome"] == "error");
    assert!(has_create, "create must be in audit log: {items:?}");
    assert!(has_delete, "delete must be in audit log: {items:?}");
    assert!(
        has_failed_reveal,
        "post-delete failed reveal must be in audit log: {items:?}"
    );
}

// ---------------------------------------------------------------------------
// 2.4.0 — multi-environment integration tests (ADR-0022).
// ---------------------------------------------------------------------------

#[tokio::test]
async fn environments_endpoint_lists_the_three_supported_envs() {
    let srv = boot().await;
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/environments", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 200);
    let v: serde_json::Value = resp.json().await.expect("json");
    let arr = v["environments"].as_array().expect("array");
    assert_eq!(arr.len(), 3);
    assert_eq!(arr[0], "dev");
    assert_eq!(arr[1], "staging");
    assert_eq!(arr[2], "production");
}

#[tokio::test]
async fn deploy_records_environment_and_list_filter_works() {
    let srv = boot().await;
    let op_token = create_user(&srv, "op", Role::Operator).await;
    // Create one dev and one staging deploy.
    let (id_dev, _) = _request_deploy_with_env(&srv, &op_token, "dev").await;
    let (id_staging, _) = _request_deploy_with_env(&srv, &op_token, "staging").await;
    // GET /v1/deploys?env=staging returns only the staging row.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/deploys?env=staging", srv.base))
        .bearer_auth(&op_token)
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 200);
    let v: serde_json::Value = resp.json().await.expect("json");
    let arr = v.as_array().expect("array");
    assert_eq!(arr.len(), 1);
    assert_eq!(arr[0]["environment"], "staging");
    assert_eq!(arr[0]["id"].as_i64().unwrap(), id_staging);
    // And the dev row's environment is recorded correctly.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/deploys/{id_dev}", srv.base))
        .bearer_auth(&op_token)
        .send()
        .await
        .expect("get");
    let v: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(v["environment"], "dev");
}

async fn _request_deploy_with_env(
    srv: &TestServer,
    token: &str,
    env: &str,
) -> (i64, serde_json::Value) {
    // One catalog per env so two
    // sequential calls (e.g. dev +
    // staging) don't collide on the
    // `sources` UNIQUE(kind, location)
    // constraint.
    let cat = srv._dir.path().join(format!("env_catalog_{env}"));
    std::fs::create_dir_all(&cat).unwrap();
    _write_approvals_catalog(&cat);
    // 2.5.3: every deploy declares a
    // target.
    let target_name = format!("env-target-{env}");
    let _ = _ensure_target(srv, env, &target_name).await;
    // P0-F-07: real `source_id` for
    // the env-specific catalog.
    let source_id = register_local_source(&srv._dir.path().join("audit.db"), &cat).await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/deploys", srv.base))
        .bearer_auth(token)
        .json(&json!({
            "source_id": source_id,
            "system_yaml": APPROVALS_SYS,
            "environment": env,
            "target": target_name,
        }))
        .send()
        .await
        .expect("post deploy");
    assert_eq!(resp.status(), 201, "request deploy: {:?}", resp);
    let v: serde_json::Value = resp.json().await.expect("json");
    (v["deploy"]["id"].as_i64().expect("id"), v)
}

// ---------------------------------------------------------------------------
// 2.5.0 — fleet integration tests (ADR-0023).
// ---------------------------------------------------------------------------

/// Helper: build the body for `POST /v1/targets`.
/// `path` and `description` are optional so a test
/// can use a smaller object.
fn _create_target_body(
    name: &str,
    env: &str,
    path: &str,
    description: Option<&str>,
) -> serde_json::Value {
    let mut body = json!({
        "name": name,
        "environment": env,
        "path": path,
    });
    if let Some(d) = description {
        body["description"] = json!(d);
    }
    body
}

#[tokio::test]
async fn admin_creates_and_lists_targets() {
    let srv = boot().await;
    // 201 on POST
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/targets", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&_create_target_body(
            "prod-blue",
            "production",
            "/srv/hermes/blue",
            Some("primary prod"),
        ))
        .send()
        .await
        .expect("create");
    assert_eq!(resp.status(), 201, "create target: {:?}", resp);
    let v: serde_json::Value = resp.json().await.expect("json");
    let id = v["id"].as_i64().expect("id");
    assert_eq!(v["name"], "prod-blue");
    assert_eq!(v["environment"], "production");
    assert_eq!(v["path"], "/srv/hermes/blue");
    assert_eq!(v["description"], "primary prod");
    // Duplicate (env, name) is rejected.
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/targets", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&_create_target_body(
            "prod-blue",
            "production",
            "/srv/hermes/other",
            None,
        ))
        .send()
        .await
        .expect("dup");
    assert_eq!(resp.status(), 400, "duplicate must be rejected");
    // LIST returns the row.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/targets", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("list");
    assert_eq!(resp.status(), 200);
    let arr: Vec<serde_json::Value> = resp.json().await.expect("arr");
    assert_eq!(arr.len(), 1);
    assert_eq!(arr[0]["id"].as_i64().unwrap(), id);
    // DELETE returns 204, then a second DELETE returns 404.
    let resp = reqwest::Client::new()
        .delete(format!("{}/v1/targets/{id}", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("delete");
    assert_eq!(resp.status(), 204);
    let resp = reqwest::Client::new()
        .delete(format!("{}/v1/targets/{id}", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("delete-2");
    assert_eq!(resp.status(), 404);
    // LIST is now empty.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/targets", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("list-empty");
    let arr: Vec<serde_json::Value> = resp.json().await.expect("arr");
    assert!(arr.is_empty(), "expected empty list, got {arr:?}");
}

#[tokio::test]
async fn list_targets_filters_by_environment() {
    let srv = boot().await;
    // Seed three targets across two environments.
    for (name, env, path) in [
        ("laptop", "dev", "/home/op/dev"),
        ("ci-runner", "dev", "/var/ci"),
        ("prod-blue", "production", "/srv/hermes/blue"),
    ] {
        let resp = reqwest::Client::new()
            .post(format!("{}/v1/targets", srv.base))
            .bearer_auth(&srv.admin_token)
            .json(&_create_target_body(name, env, path, None))
            .send()
            .await
            .expect("seed");
        assert_eq!(resp.status(), 201, "seed {name}: {:?}", resp);
    }
    // Unfiltered list returns all 3.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/targets", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("list-all");
    let arr: Vec<serde_json::Value> = resp.json().await.expect("arr");
    assert_eq!(arr.len(), 3);
    // env=dev filter returns 2.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/targets?env=dev", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("list-dev");
    let arr: Vec<serde_json::Value> = resp.json().await.expect("arr");
    assert_eq!(arr.len(), 2);
    for row in &arr {
        assert_eq!(row["environment"], "dev");
    }
    // env=production filter returns 1.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/targets?env=production", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("list-prod");
    let arr: Vec<serde_json::Value> = resp.json().await.expect("arr");
    assert_eq!(arr.len(), 1);
    assert_eq!(arr[0]["name"], "prod-blue");
    // env=staging has no rows.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/targets?env=staging", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("list-staging");
    let arr: Vec<serde_json::Value> = resp.json().await.expect("arr");
    assert!(arr.is_empty());
    // Bogus env value is rejected at the application
    // layer (parses through `Environment::parse`).
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/targets?env=qa", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("list-qa");
    assert_eq!(
        resp.status(),
        400,
        "unknown env must be a 400, not silently empty"
    );
}

#[tokio::test]
async fn deploy_with_target_records_target_id() {
    let srv = boot().await;
    let op_token = create_user(&srv, "op", Role::Operator).await;
    // Register a dev target, then deploy to it.
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/targets", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&_create_target_body("laptop", "dev", "/home/op/dev", None))
        .send()
        .await
        .expect("create target");
    assert_eq!(resp.status(), 201);
    let v: serde_json::Value = resp.json().await.expect("json");
    let target_id = v["id"].as_i64().expect("id");
    // POST /v1/deploys with target=laptop.
    let cat = srv._dir.path().join("target_catalog");
    std::fs::create_dir_all(&cat).unwrap();
    _write_approvals_catalog(&cat);
    // P0-F-07: real `source_id` for
    // the laptop catalog.
    let source_id = register_local_source(&srv._dir.path().join("audit.db"), &cat).await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/deploys", srv.base))
        .bearer_auth(&op_token)
        .json(&json!({
            "source_id": source_id,
            "system_yaml": APPROVALS_SYS,
            "environment": "dev",
            "target": "laptop",
        }))
        .send()
        .await
        .expect("post deploy");
    assert_eq!(resp.status(), 201, "deploy with target: {:?}", resp);
    let v: serde_json::Value = resp.json().await.expect("json");
    let deploy_id = v["deploy"]["id"].as_i64().expect("deploy id");
    assert_eq!(v["deploy"]["target_id"].as_i64(), Some(target_id));
    assert_eq!(v["deploy"]["environment"], "dev");
    // GET /v1/deploys/:id round-trips.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/deploys/{deploy_id}", srv.base))
        .bearer_auth(&op_token)
        .send()
        .await
        .expect("get");
    let v: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(v["target_id"].as_i64(), Some(target_id));
}

#[tokio::test]
async fn deploy_with_unknown_target_is_400() {
    let srv = boot().await;
    let op_token = create_user(&srv, "op", Role::Operator).await;
    let cat = srv._dir.path().join("missing_target_catalog");
    std::fs::create_dir_all(&cat).unwrap();
    _write_approvals_catalog(&cat);
    // P0-F-07: real `source_id` so
    // the test isolates the
    // target-not-found failure path
    // (instead of failing on
    // source-not-registered first).
    let source_id = register_local_source(&srv._dir.path().join("audit.db"), &cat).await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/deploys", srv.base))
        .bearer_auth(&op_token)
        .json(&json!({
            "source_id": source_id,
            "system_yaml": APPROVALS_SYS,
            "environment": "dev",
            "target": "this-target-does-not-exist",
        }))
        .send()
        .await
        .expect("post deploy");
    assert_eq!(
        resp.status(),
        400,
        "unknown target must be a 400, not a 201/500"
    );
    let v: serde_json::Value = resp.json().await.expect("json");
    let err = v["error"].as_str().unwrap_or("");
    assert!(
        err.contains("not found"),
        "expected `not found` error, got: {err}"
    );
    // The deploy must NOT have been created.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/deploys", srv.base))
        .bearer_auth(&op_token)
        .send()
        .await
        .expect("list");
    let arr: Vec<serde_json::Value> = resp.json().await.expect("arr");
    assert!(
        arr.is_empty(),
        "failed target lookup must not leave a pending_deploys row: {arr:?}"
    );
}

// ---------------------------------------------------------------------------
// 2.7.8 — OIDC token refresh + logout
// (ADR-0036). The mock client is in
// effect, so the IdP's `end_session_endpoint`
// is None; the logout endpoint returns
// 200 with `{"message": "logged out locally"}`.
// ---------------------------------------------------------------------------

#[tokio::test]
async fn oidc_refresh_endpoint_returns_new_token_and_expiry() {
    let srv = boot().await;
    // The 2.7.6 framework provisions an
    // OIDC user via `provision_user_from_claims`
    // (called from the `/callback`
    // handler). For the test we go
    // straight to the underlying repo
    // to seed a user with an
    // `external_id`. (The 2.7.8
    // surface does not need a separate
    // `create_oidc_user` helper.)
    let users = UserRepository::new(connect_helper(&srv).await);
    // P0-F-01: the test user MUST have
    // `external_id` equal to the sub
    // the mock OIDC client returns
    // from `refresh()`. Otherwise the
    // post-fix subject-binding check
    // (refreshed.claims.sub ==
    // user.external_id) would correctly
    // reject the refresh as a subject
    // confusion attack. The mock
    // returns `sub = "oidc:test:user-1"`,
    // so we seed the user with that
    // external_id.
    let user = users
        .create_with_external_id("alice", Role::Operator, "oidc:test:user-1")
        .await
        .expect("create");
    users
        .set_token_expiry(user.id, "2020-01-01T00:00:00Z")
        .await
        .expect("expiry");
    // Refresh: a public endpoint.
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/auth/oidc/refresh", srv.base))
        .json(&json!({
            "refresh_token": "the-mock-refresh-token",
            "sub": "oidc:test:user-1",
        }))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 200);
    let v: serde_json::Value = resp.json().await.expect("json");
    assert!(v["token"].is_string());
    assert!(v["expires_at"].is_string());
    // The new token must NOT be the
    // old (already-invalidated) one.
    let new_token = v["token"].as_str().expect("token");
    assert!(!new_token.is_empty());
    // The user can be looked up by
    // the new token.
    let still_valid = users
        .find_by_token(new_token)
        .await
        .expect("find")
        .expect("present");
    assert_eq!(still_valid.id, user.id);
    // The new expiry is approximately
    // `now + 1h` (the mock client).
    let parsed =
        chrono::DateTime::parse_from_rfc3339(v["expires_at"].as_str().unwrap()).expect("rfc3339");
    let now = chrono::Utc::now();
    assert!(parsed > now);
    assert!(parsed < now + chrono::Duration::hours(2));
}

// P0-F-01 (TZ #1 §6 F-01, CWE-287,
// Appendix A.1): the refresh endpoint
// MUST refuse a refresh whose IdP-returned
// `sub` does not match the local user's
// `external_id`. The pre-fix code did not
// perform this check, allowing a
// subject-confusion attack:
//
//   1. Alice (sub=alice) has refresh
//      token RT_A.
//   2. Attacker (who is Alice) calls
//      POST /v1/auth/oidc/refresh
//      with `{ sub: bob, refresh_token: RT_A }`.
//   3. Pre-fix: the handler finds bob's
//      local user by `sub=bob`,
//      refreshes at the IdP using RT_A
//      (which the IdP validates as
//      belonging to Alice), gets back
//      claims with sub=alice, and rotates
//      bob's local token hash to a
//      freshly generated value. Alice now
//      holds a fresh local bearer that
//      authenticates as bob.
//   4. Post-fix: the handler compares
//      `refreshed.claims.sub` to
//      `user.external_id` and rejects
//      with 401 oidc.refresh.subject_mismatch.
//
// The mock OIDC client always returns
// sub="oidc:test:user-1", so the
// attack scenario is: local user with
// external_id="bob" + refresh with
// sub="bob" → 401 (mock will return
// alice, mismatch).
#[tokio::test]
async fn oidc_refresh_rejects_subject_mismatch() {
    let srv = boot().await;
    let users = UserRepository::new(connect_helper(&srv).await);
    // Seed bob's local user. bob's
    // external_id is "bob"; the mock OIDC
    // client will return sub="oidc:test:user-1"
    // (Alice's sub), which does not match
    // → 401.
    let _bob = users
        .create_with_external_id("bob", Role::Operator, "bob")
        .await
        .expect("create");
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/auth/oidc/refresh", srv.base))
        .json(&json!({
            "refresh_token": "the-mock-refresh-token",
            "sub": "bob",
        }))
        .send()
        .await
        .expect("post");
    assert_eq!(
        resp.status(),
        401,
        "P0-F-01: refresh with mismatched sub must return 401, \
         not 200 (subject confusion attack)"
    );
    let v: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(v["code"], "oidc.refresh.subject_mismatch");
}

#[tokio::test]
async fn oidc_refresh_with_unknown_sub_returns_404() {
    let srv = boot().await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/auth/oidc/refresh", srv.base))
        .json(&json!({
            "refresh_token": "any",
            "sub": "no-such-user",
        }))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 404);
}

#[tokio::test]
async fn oidc_logout_endpoint_returns_200_locally() {
    let srv = boot().await;
    // 2.11.0 (P2-LOGOUT-01, CWE-352):
    // the endpoint changed from GET to
    // POST (CSRF hardening). Anonymous
    // logout (no body) still returns
    // 200 because the mock client has
    // no end_session_endpoint and
    // `revoke_refresh_token` is a
    // no-op on an empty body.
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/auth/oidc/logout", srv.base))
        .body("")
        .header("content-type", "application/json")
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 200);
    let v: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(v["message"], "logged out locally");
}

#[tokio::test]
async fn oidc_logout_with_bearer_invalidates_local_token() {
    let srv = boot().await;
    let users = UserRepository::new(connect_helper(&srv).await);
    let user = users
        .create_with_external_id("bob", Role::Operator, "sub-bob")
        .await
        .expect("create");
    // Issue a local bearer and store
    // the hash. The mock client
    // doesn't issue tokens, so we
    // rotate the user's token via
    // the API to get a plain one.
    users
        .set_token_expiry(user.id, "2030-01-01T00:00:00Z")
        .await
        .expect("expiry");
    let plain = users
        .rotate_token(user.id)
        .await
        .expect("rotate")
        .expect("present");
    // Logout with the bearer.
    // 2.11.0 (P2-LOGOUT-01): POST +
    // optional `refresh_token` in the
    // JSON body.
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/auth/oidc/logout", srv.base))
        .bearer_auth(&plain)
        .body(r#"{"refresh_token":"opaque-mock-refresh"}"#)
        .header("content-type", "application/json")
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 200);
    // The local token must no longer
    // work.
    let after = users.find_by_token(&plain).await.expect("find");
    assert!(after.is_none(), "logout must invalidate the local token");
}

#[tokio::test]
async fn expired_token_returns_401() {
    let srv = boot().await;
    let users = UserRepository::new(connect_helper(&srv).await);
    let user = users
        .create_with_external_id("carol", Role::Operator, "sub-carol")
        .await
        .expect("create");
    users
        .set_token_expiry(user.id, "2020-01-01T00:00:00Z")
        .await
        .expect("expiry");
    let plain = users
        .rotate_token(user.id)
        .await
        .expect("rotate")
        .expect("present");
    // Any authed endpoint should
    // 401 because the token is
    // expired.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/audit", srv.base))
        .bearer_auth(&plain)
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 401);
}

/// 2.7.8 helper: open a fresh
/// connection to the test server's
/// in-memory DB. The TestServer holds
/// the connection; the helper just
/// returns a clone of the pool. (We
/// can't easily share `state.db` from
/// the test helper, so we open a
/// second connection to the same
/// file. For in-memory tests, the
/// DB file lives under
/// `srv._dir`.)
async fn connect_helper(srv: &TestServer) -> sqlx::SqlitePool {
    let path = srv._dir.path().join("audit.db");
    let db = agent_dep_core::infrastructure::sqlite::connect(&path)
        .await
        .expect("connect");
    db.migrate().await.expect("migrate");
    db.pool().clone()
}

/// P0-F-07 test helper: register a local
/// source pointing at `path` and return
/// its UUID. The plan/deploy endpoints
/// resolve the source by UUID via
/// `compute_plan_from_source` /
/// `compute_deploy_plan_from_source`; the
/// filesystem path is read from the DB,
/// not from the request body.
async fn register_local_source(db_path: &std::path::Path, path: &std::path::Path) -> String {
    use agent_dep_core::infrastructure::sqlite::connect;
    let db = connect(db_path).await.expect("connect");
    db.migrate().await.expect("migrate");
    let pool = db.pool().clone();
    let id = uuid::Uuid::new_v4().to_string();
    sqlx::query(
        "INSERT INTO sources (id, kind, location, created_at) \
         VALUES (?1, 'local', ?2, '2026-01-01T00:00:00Z')",
    )
    .bind(&id)
    .bind(path.to_string_lossy().as_ref())
    .execute(&pool)
    .await
    .expect("insert source");
    id
}

// ---------------------------------------------------------------------------
// 2.11.0 (P1-D-01d, TZ #1 §10 / D-01d,
// CWE-494 Download of Code Without
// Integrity Check): the
// `source_snapshot_id` field on
// `POST /v1/systems/plan` and
// `POST /v1/deploys`.
// ---------------------------------------------------------------------------

/// P1-D-01d test helper: write a
/// catalog with a single `be@1.0.0`
/// agent and an `fe@1.0.0` agent.
fn _write_snapshot_catalog(cat: &std::path::Path) {
    use std::fs;
    fs::create_dir_all(cat.join("agents/engineering")).unwrap();
    fs::write(
        cat.join("divisions.json"),
        r#"{"divisions":[{"id": "engineering", "label": "Eng", "order": 0}]}"#,
    )
    .unwrap();
    let be_md = r#"---
id: be
name: Backend
display_name: Backend
division: engineering
role: backend
description: be
version: 1.0.0
sensitive: false
activation_phrases: []
tools: []
---

You are be.
"#;
    fs::write(cat.join("agents/engineering/be.md"), be_md).unwrap();
    let fe_md = r#"---
id: fe
name: Frontend
display_name: Frontend
division: engineering
role: frontend
description: fe
version: 1.0.0
sensitive: false
activation_phrases: []
tools: []
---

You are fe.
"#;
    fs::write(cat.join("agents/engineering/fe.md"), fe_md).unwrap();
}

/// P1-D-01d test helper: register
/// a local source for `cat_path`
/// AND write a `source_snapshots`
/// row + `agents` rows for the
/// agents in the catalog. Returns
/// `(source_id, snapshot_id)`.
/// Tests that need a stored
/// snapshot call this once at the
/// top of their setup.
async fn register_local_source_with_snapshot(
    srv: &TestServer,
    cat_path: &std::path::Path,
) -> (String, String) {
    use agent_dep_core::application::ingest::IngestService;
    use agent_dep_core::domain::source::{Source, SourceKind};
    use agent_dep_core::infrastructure::repository::IngestRepository;
    let pool = connect_helper(srv).await;
    // 1. Insert the `sources` row.
    let source_id = uuid::Uuid::new_v4();
    sqlx::query(
        "INSERT INTO sources (id, kind, location, created_at) \
         VALUES (?1, 'local', ?2, '2026-01-01T00:00:00Z')",
    )
    .bind(source_id.to_string())
    .bind(cat_path.to_string_lossy().as_ref())
    .execute(&pool)
    .await
    .expect("insert source");
    // 2. Ingest the catalog into an
    //    `IngestResult`.
    let source = Source::new(SourceKind::local(cat_path.to_path_buf()));
    let (result, report) = IngestService::new()
        .ingest_local(&source, None)
        .expect("ingest_local");
    // 3. Persist the snapshot +
    //    child rows. `record_snapshot`
    //    supersedes any current
    //    `active` row for this source
    //    and inserts the new one.
    let snap_id = result.snapshot.id;
    let repo = IngestRepository::new(pool.clone());
    repo.record_snapshot(source_id, &result, &report)
        .await
        .expect("record_snapshot");
    (source_id.to_string(), snap_id.to_string())
}

/// P1-D-01d: `POST /v1/systems/plan`
/// with `source_snapshot_id` looks
/// up the stored snapshot and
/// composes against its agents. The
/// stored snapshot must be the
/// catalog we registered, not the
/// post-snapshot edits on disk.
#[tokio::test]
async fn plan_endpoint_uses_source_snapshot_id_when_supplied() {
    let srv = boot().await;
    let cat = srv._dir.path().join("snap_plan_cat");
    _write_snapshot_catalog(&cat);
    // Register the source + write
    // the snapshot.
    let (source_id, snap_id) = register_local_source_with_snapshot(&srv, &cat).await;
    // 2.11.0 (P1-D-01d, CWE-494):
    // MUTATE the catalog on disk.
    // Any plan that re-ingests the
    // working copy would now see the
    // mutated agents and fail. A plan
    // that uses the stored snapshot
    // continues to compose against
    // the pre-mutation agents.
    std::fs::remove_dir_all(cat.join("agents")).unwrap();
    std::fs::create_dir_all(cat.join("agents/engineering")).unwrap();
    std::fs::write(
        cat.join("agents/engineering/zzz.md"),
        r#"---
id: zzz
name: Zzz
display_name: Zzz
division: engineering
role: zzz
description: zzz
version: 1.0.0
sensitive: false
activation_phrases: []
tools: []
---

zzz body.
"#,
    )
    .unwrap();
    let sys = r#"apiVersion: agent-dep/v1
kind: System
metadata:
  id: test-sys
  name: test
spec:
  source: ./catalog
  runtime_type: hermes
  agents:
    - ref: be@1.0.0
"#;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/systems/plan", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({
            "source_id": source_id,
            "system_yaml": sys,
            "source_snapshot_id": snap_id,
        }))
        .send()
        .await
        .expect("post");
    let status = resp.status();
    let body_text = resp.text().await.unwrap_or_default();
    assert_eq!(
        status, 200,
        "stored-snapshot plan should succeed (P1-D-01d): status={status} body={body_text}"
    );
    let v: serde_json::Value = serde_json::from_str(&body_text).expect("json");
    let writes = v["writes"].as_array().expect("writes");
    assert_eq!(writes.len(), 1, "exactly one write (be)");
    assert_eq!(writes[0]["agent_ref"], "be@1.0.0");
}

/// P1-D-01d: an unknown
/// `source_snapshot_id` is rejected
/// with 400 (not 500 — the failure
/// mode is caller error, not a
/// server bug). The server MUST
/// NOT silently fall back to
/// re-ingest (that would let a
/// caller pick the plan they want
/// by quoting a non-existent snap
/// id).
#[tokio::test]
async fn plan_endpoint_with_unknown_source_snapshot_id_returns_400() {
    let srv = boot().await;
    let cat = srv._dir.path().join("snap_unknown_cat");
    _write_snapshot_catalog(&cat);
    let (source_id, _snap_id) = register_local_source_with_snapshot(&srv, &cat).await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/systems/plan", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({
            "source_id": source_id,
            "system_yaml": r#"apiVersion: agent-dep/v1
kind: System
metadata:
  id: test-sys
  name: test
spec:
  source: ./catalog
  runtime_type: hermes
  agents:
    - ref: be@1.0.0
"#,
            "source_snapshot_id": "00000000-0000-0000-0000-deadbeefcafe",
        }))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 400);
}

/// P1-D-01d (CWE-345 source
/// confusion): a snapshot that
/// belongs to source A MUST NOT be
/// usable in a plan that names
/// source B. The server returns
/// 400.
#[tokio::test]
async fn plan_endpoint_with_cross_source_snapshot_id_returns_400() {
    let srv = boot().await;
    let cat_a = srv._dir.path().join("snap_xsrc_cat_a");
    let cat_b = srv._dir.path().join("snap_xsrc_cat_b");
    _write_snapshot_catalog(&cat_a);
    // `cat_b` exists too (so the
    // sources table accepts it as
    // a real location), but is
    // empty — the plan will fail
    // anyway because the snapshot
    // check runs first. The point
    // of the test is the CWE-345
    // guard, not the ingest path.
    std::fs::create_dir_all(&cat_b).unwrap();
    // Register source A (this one
    // gets the snapshot).
    let (_source_id_a, snap_id_a) = register_local_source_with_snapshot(&srv, &cat_a).await;
    // Register source B at a
    // different path (the
    // `sources` table has UNIQUE
    // (kind, location)).
    let source_id_b = uuid::Uuid::new_v4().to_string();
    {
        let pool = connect_helper(&srv).await;
        sqlx::query(
            "INSERT INTO sources (id, kind, location, created_at) \
             VALUES (?1, 'local', ?2, '2026-01-01T00:00:00Z')",
        )
        .bind(&source_id_b)
        .bind(cat_b.to_string_lossy().as_ref())
        .execute(&pool)
        .await
        .expect("insert source B");
    }
    // Plan against B + A's snap.
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/systems/plan", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({
            "source_id": source_id_b,
            "system_yaml": r#"apiVersion: agent-dep/v1
kind: System
metadata:
  id: test-sys
  name: test
spec:
  source: ./catalog
  runtime_type: hermes
  agents:
    - ref: be@1.0.0
"#,
            "source_snapshot_id": snap_id_a,
        }))
        .send()
        .await
        .expect("post");
    assert_eq!(
        resp.status(),
        400,
        "cross-source snapshot MUST be 400 (CWE-345), got {}",
        resp.status()
    );
}

/// P1-D-01d: `POST /v1/deploys`
/// with `source_snapshot_id`
/// populates
/// `pending_deploys.source_snapshot_id`
/// in the persisted row. This is
/// the field that the
/// `mark_applied` freshness check
/// (CWE-494) reads to verify the
/// snapshot still exists at apply
/// time.
#[tokio::test]
async fn request_deploy_with_source_snapshot_id_persists_it() {
    let srv = boot().await;
    let cat = srv._dir.path().join("snap_deploy_cat");
    _write_snapshot_catalog(&cat);
    let (source_id, snap_id) = register_local_source_with_snapshot(&srv, &cat).await;
    // 2.5.3: create a target so
    // `request_deploy` accepts the
    // request.
    let _ = _ensure_target(&srv, "dev", "snap-target").await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/deploys", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({
            "source_id": source_id,
            "system_yaml": r#"apiVersion: agent-dep/v1
kind: System
metadata:
  id: test-sys
  name: test
spec:
  source: ./catalog
  runtime_type: hermes
  agents:
    - ref: be@1.0.0
"#,
            "environment": "dev",
            "target": "snap-target",
            "source_snapshot_id": snap_id,
        }))
        .send()
        .await
        .expect("post deploy");
    let status = resp.status();
    let body_text = resp.text().await.unwrap_or_default();
    assert_eq!(
        status, 201,
        "deploy should succeed: status={status} body={body_text}"
    );
    let v: serde_json::Value = serde_json::from_str(&body_text).expect("json");
    // The response surfaces the
    // resolved snap id in the
    // `deploy` view (P1-D-01d).
    assert_eq!(
        v["deploy"]["source_snapshot_id"].as_str(),
        Some(snap_id.as_str()),
        "deploy view must include the resolved source_snapshot_id"
    );
    // Also: the audit row records
    // it. 2.10.0 (P1-AUD-FIX,
    // CWE-778) reverted
    // `request_deploy` to
    // `record_sync`, so the row is
    // durable by the time the 201
    // returns — no sleep needed.
    let audit: serde_json::Value = {
        let pool = connect_helper(&srv).await;
        let row: (String, String) = sqlx::query_as(
            "SELECT actor, details FROM audit_log WHERE action = 'POST /v1/deploys' \
             ORDER BY id DESC LIMIT 1",
        )
        .fetch_one(&pool)
        .await
        .expect("audit row");
        json!({"actor": row.0, "details": row.1})
    };
    let details: serde_json::Value =
        serde_json::from_str(audit["details"].as_str().unwrap_or("{}")).expect("details json");
    assert_eq!(
        details["source_snapshot_id"].as_str(),
        Some(snap_id.as_str()),
        "audit row must record the resolved source_snapshot_id"
    );
    // And the DB row matches.
    let pool = connect_helper(&srv).await;
    let db_snap: Option<String> = sqlx::query_scalar(
        "SELECT source_snapshot_id FROM pending_deploys \
         WHERE id = ?1",
    )
    .bind(v["deploy"]["id"].as_i64().unwrap())
    .fetch_one(&pool)
    .await
    .expect("db snap");
    assert_eq!(db_snap.as_deref(), Some(snap_id.as_str()));
}

/// P1-D-01d: a request_deploy with
/// an unknown `source_snapshot_id`
/// returns 400 (not 500). The
/// caller quoted a snap id that
/// does not exist.
#[tokio::test]
async fn request_deploy_with_unknown_source_snapshot_id_returns_400() {
    let srv = boot().await;
    let cat = srv._dir.path().join("snap_deploy_unknown_cat");
    _write_snapshot_catalog(&cat);
    let (source_id, _snap_id) = register_local_source_with_snapshot(&srv, &cat).await;
    let _ = _ensure_target(&srv, "dev", "snap-unknown-target").await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/deploys", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({
            "source_id": source_id,
            "system_yaml": "x",
            "environment": "dev",
            "target": "snap-unknown-target",
            "source_snapshot_id": "00000000-0000-0000-0000-deadbeefcafe",
        }))
        .send()
        .await
        .expect("post deploy");
    assert_eq!(resp.status(), 400);
}

/// P1-D-01d (CWE-345): a request
/// that names `source_id = B` but
/// `source_snapshot_id` from
/// `source_id = A` is rejected
/// with 400.
#[tokio::test]
async fn request_deploy_with_cross_source_snapshot_id_returns_400() {
    let srv = boot().await;
    let cat_a = srv._dir.path().join("snap_deploy_xsrc_cat_a");
    let cat_b = srv._dir.path().join("snap_deploy_xsrc_cat_b");
    _write_snapshot_catalog(&cat_a);
    std::fs::create_dir_all(&cat_b).unwrap();
    let (_source_id_a, snap_id_a) = register_local_source_with_snapshot(&srv, &cat_a).await;
    // Register source B at a
    // different path (`sources`
    // has UNIQUE (kind, location)).
    let source_id_b = uuid::Uuid::new_v4().to_string();
    {
        let pool = connect_helper(&srv).await;
        sqlx::query(
            "INSERT INTO sources (id, kind, location, created_at) \
             VALUES (?1, 'local', ?2, '2026-01-01T00:00:00Z')",
        )
        .bind(&source_id_b)
        .bind(cat_b.to_string_lossy().as_ref())
        .execute(&pool)
        .await
        .expect("insert source B");
    }
    let _ = _ensure_target(&srv, "dev", "snap-xsrc-target").await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/deploys", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({
            "source_id": source_id_b,
            "system_yaml": "x",
            "environment": "dev",
            "target": "snap-xsrc-target",
            "source_snapshot_id": snap_id_a,
        }))
        .send()
        .await
        .expect("post deploy");
    assert_eq!(resp.status(), 400);
}

/// P1-D-01d: a request_deploy
/// without `source_snapshot_id`
/// (the legacy path) still
/// succeeds. The persisted row
/// has `source_snapshot_id =
/// NULL` and the audit row's
/// `source_snapshot_id` field is
/// `null`. This is the
/// backward-compat path for the
/// 2.11.0 CLI / pre-snapshot SPA.
#[tokio::test]
async fn request_deploy_without_source_snapshot_id_uses_reingest_path() {
    let srv = boot().await;
    let cat = srv._dir.path().join("snap_legacy_cat");
    _write_snapshot_catalog(&cat);
    let (source_id, _snap_id) = register_local_source_with_snapshot(&srv, &cat).await;
    let _ = _ensure_target(&srv, "dev", "snap-legacy-target").await;
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/deploys", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({
            "source_id": source_id,
            "system_yaml": r#"apiVersion: agent-dep/v1
kind: System
metadata:
  id: test-sys
  name: test
spec:
  source: ./catalog
  runtime_type: hermes
  agents:
    - ref: be@1.0.0
"#,
            "environment": "dev",
            "target": "snap-legacy-target",
        }))
        .send()
        .await
        .expect("post deploy");
    let status = resp.status();
    let body_text = resp.text().await.unwrap_or_default();
    assert_eq!(
        status, 201,
        "legacy path should still succeed: status={status} body={body_text}"
    );
    let v: serde_json::Value = serde_json::from_str(&body_text).expect("json");
    // No `source_snapshot_id`
    // in the response — the legacy
    // path leaves the column NULL.
    assert!(
        v["deploy"]["source_snapshot_id"].is_null(),
        "legacy path must persist source_snapshot_id = null, got {:?}",
        v["deploy"]["source_snapshot_id"]
    );
}

// ---------------------------------------------------------------------------
// 2.10.0 (B2, audit CWE-352
// Cross-Site Request Forgery): the
// session-cookie auth path must reject
// state-changing requests (POST / PUT /
// DELETE) that lack a matching
// `X-CSRF-Token` header. Bearer auth
// is exempt (bearer is not
// CSRF-vulnerable).
// ---------------------------------------------------------------------------

/// Test helper: create a session
/// for `user_id` in the test DB and
/// return `(session_id, csrf_token)`.
/// The caller sends the session id in
/// a `Cookie: agency_session=<sid>`
/// header and the csrf_token in an
/// `X-CSRF-Token` header.
async fn _create_session(srv: &TestServer, user_id: i64) -> (String, String) {
    use agent_dep_core::infrastructure::repository::sessions_repository::SessionRepository;
    let repo = SessionRepository::new(connect_helper(srv).await);
    let (sid, row) = repo
        .create(user_id, None, None)
        .await
        .expect("create session");
    (sid, row.csrf_token)
}

#[tokio::test]
async fn csrf_mutation_without_token_returns_403() {
    // 2.10.0 (B2): session-cookie
    // auth + POST without
    // `X-CSRF-Token` must be
    // rejected with 403. This is
    // the headline CSRF defence:
    // any cross-origin form post
    // that triggers our session
    // cookie is denied because
    // the attacker cannot read /
    // forge the csrf_token from
    // their page.
    let srv = boot().await;
    // Create a session for `admin`.
    // (admin already has user id 1
    // from boot_default_state.)
    let (sid, _csrf) = _create_session(&srv, 1).await;
    // Build a cookie header that
    // the auth middleware will
    // parse.
    let cookie = format!("agency_session={sid}");
    // POST /v1/users without
    // X-CSRF-Token. The handler is
    // `create_user` (Admin-only,
    // mutation). The CSRF
    // middleware should reject
    // BEFORE the role guard, so
    // this is a 403, not a 401.
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/users", srv.base))
        .header(axum::http::header::COOKIE, &cookie)
        .json(&json!({ "name": "newuser", "role": "viewer" }))
        .send()
        .await
        .expect("post");
    let status = resp.status();
    let body = resp.text().await.unwrap_or_default();
    assert_eq!(
        status, 403,
        "missing CSRF token must be 403; got body={body}"
    );
    let v: serde_json::Value = serde_json::from_str(&body).expect("json");
    assert_eq!(v["code"], "csrf.mismatch");
    // The audit log records the
    // rejection. Wait briefly for
    // the async flush.
    tokio::time::sleep(std::time::Duration::from_millis(100)).await;
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/audit?limit=200", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("get audit");
    let v: serde_json::Value = resp.json().await.expect("json");
    let items = v["items"].as_array().expect("items");
    let csrf_row = items
        .iter()
        .find(|r| r["action"] == "POST /v1/users" && r["outcome"] == "error")
        .expect("csrf mismatch row must be in audit log");
    assert_eq!(csrf_row["target"].as_str(), Some("csrf"));
}

#[tokio::test]
async fn csrf_mutation_with_wrong_token_returns_403() {
    // 2.10.0 (B2): wrong
    // X-CSRF-Token (constant-time
    // compare fails) returns 403.
    // This catches a misconfigured
    // SPA that sends a stale or
    // cross-session token.
    let srv = boot().await;
    let (sid, _csrf) = _create_session(&srv, 1).await;
    let cookie = format!("agency_session={sid}");
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/users", srv.base))
        .header(axum::http::header::COOKIE, &cookie)
        .header("X-CSRF-Token", "this-is-not-the-real-token")
        .json(&json!({ "name": "newuser2", "role": "viewer" }))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 403);
    let v: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(v["code"], "csrf.mismatch");
}

#[tokio::test]
async fn csrf_mutation_with_correct_token_succeeds() {
    // 2.10.0 (B2): the happy path
    // — session cookie + correct
    // X-CSRF-Token unlocks the
    // mutation. The handler
    // receives the authenticated
    // user (the admin) and the
    // create_user call succeeds.
    let srv = boot().await;
    let (sid, csrf) = _create_session(&srv, 1).await;
    let cookie = format!("agency_session={sid}");
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/users", srv.base))
        .header(axum::http::header::COOKIE, &cookie)
        .header("X-CSRF-Token", &csrf)
        .json(&json!({ "name": "newuser3", "role": "viewer" }))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 201, "valid session + csrf must succeed");
    let v: serde_json::Value = resp.json().await.expect("json");
    assert_eq!(v["name"], "newuser3");
}

#[tokio::test]
async fn csrf_safe_methods_do_not_require_token() {
    // 2.10.0 (B2): GET requests
    // never need X-CSRF-Token —
    // they're not state-changing.
    // The CSRF middleware short-
    // circuits on safe methods.
    let srv = boot().await;
    let (sid, _csrf) = _create_session(&srv, 1).await;
    let cookie = format!("agency_session={sid}");
    // No X-CSRF-Token; GET must
    // still succeed.
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/users", srv.base))
        .header(axum::http::header::COOKIE, &cookie)
        .send()
        .await
        .expect("get");
    assert_eq!(resp.status(), 200);
}

#[tokio::test]
async fn bearer_pre_oidc_user_is_rejected_without_fallback_flag() {
    // 2.11.0 (B1, audit CWE-798):
    // boot() sets
    // `AGENCY_BEARER_FALLBACK=1`
    // for backward-compat. We boot
    // first, then clear the env
    // var (so the next request sees
    // `false`), and finally make
    // the request. The env var is
    // read per-request in
    // `bearer_fallback_enabled()`.
    // SAFETY: see boot() for the
    // thread-safety discussion.
    let srv = boot().await;
    unsafe {
        std::env::remove_var("AGENCY_BEARER_FALLBACK");
    }
    // srv.admin_token is the
    // pre-OIDC admin's bearer
    // (token_expires_at IS NULL).
    let resp = reqwest::Client::new()
        .get(format!("{}/v1/users", srv.base))
        .bearer_auth(&srv.admin_token)
        .send()
        .await
        .expect("get");
    assert_eq!(
        resp.status(),
        401,
        "B1: pre-OIDC bearer must be REJECTED when fallback is OFF"
    );
    // 2.11.0 (B1): the WARN-AND-REJECT
    // reasoning is in the audit
    // row, not the 401 body. The
    // body is intentionally
    // generic to avoid leaking
    // that the operator has the
    // legacy fallback disabled.
    // Read the audit row directly
    // from the DB (the GET
    // /v1/audit endpoint itself
    // is also rejected by the
    // same B1 check above, so a
    // query bypass via
    // `connect_helper` is the
    // only way to verify the
    // row landed).
    let pool = connect_helper(&srv).await;
    let row: (String, String) = sqlx::query_as(
        "SELECT actor, details FROM audit_log \
         WHERE action = 'GET /v1/users' AND outcome = 'error' \
         ORDER BY id DESC LIMIT 1",
    )
    .fetch_one(&pool)
    .await
    .expect("audit row");
    assert_eq!(row.0, "anonymous", "B1: rejected actor must be anonymous");
    let details: serde_json::Value = serde_json::from_str(&row.1).expect("details json");
    assert!(
        details["reason"]
            .as_str()
            .unwrap_or("")
            .contains("AGENCY_BEARER_FALLBACK"),
        "B1: audit row must mention the fallback flag, got: {details}"
    );
    // Re-arm for the rest of the
    // suite.
    unsafe {
        std::env::set_var("AGENCY_BEARER_FALLBACK", "1");
    }
}

#[tokio::test]
async fn csrf_bearer_auth_bypasses_check() {
    // 2.10.0 (B2): bearer auth
    // (legacy 2.0.0-2.7.7 path) is
    // exempt from CSRF because
    // the attacker cannot read the
    // bearer token from a victim's
    // browser. The middleware
    // short-circuits on
    // `CsrfContext(None)`.
    let srv = boot().await;
    // No cookie, no X-CSRF-Token;
    // just bearer. Should succeed.
    let resp = reqwest::Client::new()
        .post(format!("{}/v1/users", srv.base))
        .bearer_auth(&srv.admin_token)
        .json(&json!({ "name": "bearer-user", "role": "viewer" }))
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), 201);
}
