//! 2.7.7 (ADR-0035) OIDC wire-protocol client.
//!
//! The 2.7.6 framework in `super::oidc` is
//! responsible for the surrounding plumbing
//! (config, state map, role mapping, user
//! provisioning, axum handlers). This module
//! is the *transport* layer: it builds the
//! `/authorize` URL, exchanges the
//! authorization code for tokens, validates
//! the ID token against the JWKS, and
//! extracts claims.
//!
//! Two implementations of [`OidcClient`]:
//! - [`RealOidcClient`]: production. Uses
//!   the `openidconnect` crate + the
//!   `reqwest` async client.
//! - [`MockOidcClient`]: tests + the 2.7.6
//!   `AGENCY_OIDC_MOCK=1` default.
//!
//! The `callback_handler` in `super::oidc`
//! dispatches to whichever is configured.

use std::sync::Arc;

use agent_dep_core::error::{CoreError, CoreResult};
use async_trait::async_trait;
use serde::Deserialize;

use crate::oidc::OidcConfig;

/// What the `/v1/auth/oidc/callback` handler
/// hands to the client to exchange.
#[derive(Debug, Clone)]
pub struct CallbackInput {
    /// The `code` query param from the IdP
    /// redirect.
    pub code: String,
    /// The `state` query param from the IdP
    /// redirect. The 2.7.6 framework has
    /// already validated it against
    /// `OidcPending` and removed the entry.
    /// The PKCE verifier is no longer needed
    /// here — the `RealOidcClient` looks it
    /// up via the state token, but in 2.7.7
    /// we pass the verifier explicitly (the
    /// framework retains the
    /// `(state -> PendingAuth { pkce_verifier,
    /// nonce, ... })` map so the client can
    /// look it up).
    pub state: String,
    /// The PKCE verifier corresponding to
    /// `state`. The 2.7.6 callback handler
    /// pulls this from `OidcPending` before
    /// dropping the entry.
    pub pkce_verifier: String,
    /// The nonce corresponding to `state`.
    pub nonce: String,
}

/// What the client returns on success. The
/// `callback_handler` forwards the claims to
/// `provision_user_from_claims`.
#[derive(Debug, Clone)]
pub struct TokenClaims {
    /// The IdP `sub` claim — the stable
    /// user identifier. Becomes
    /// `users.external_id`.
    pub sub: String,
    /// Optional email.
    pub email: Option<String>,
    /// Optional preferred username.
    pub preferred_username: Option<String>,
    /// The role-claim value (typically
    /// `groups` for Okta / Keycloak /
    /// Auth0). The shape is normalised
    /// upstream by `super::oidc::map_claims_to_role`.
    pub role_claim_value: serde_json::Value,
}

/// 2.7.8 (ADR-0036): what
/// `OidcClient::refresh` returns. The
/// framework re-issues a local bearer
/// token from the new claims and
/// updates `users.token_expires_at`.
#[derive(Debug, Clone)]
pub struct RefreshedTokens {
    pub claims: TokenClaims,
    /// RFC 3339 timestamp at which the
    /// IdP's `access_token` (and the
    /// local bearer) expires. The
    /// framework stores this in
    /// `users.token_expires_at`.
    pub expires_at: String,
    /// New IdP `refresh_token` (if the
    /// IdP rotated it). The framework
    /// does NOT store this (it cannot
    /// keep a 2.x-state-secret); the
    /// SPA holds it client-side.
    pub new_refresh_token: Option<String>,
}

/// The wire-protocol abstraction. Uses
/// `async_trait` for object-safety
/// (so we can store `Arc<dyn OidcClient>`).
#[async_trait]
pub trait OidcClient: Send + Sync {
    /// Build the IdP `/authorize` URL. The
    /// `state` and `code_challenge` are
    /// already generated by the framework;
    /// the client just assembles the URL.
    fn authorize_url(
        &self,
        state: &str,
        code_challenge: &str,
        nonce: &str,
    ) -> CoreResult<String>;

    /// Exchange the authorization code for
    /// tokens, validate the ID token, and
    /// extract claims.
    async fn exchange_code(
        &self,
        input: CallbackInput,
    ) -> CoreResult<TokenClaims>;

    /// 2.7.8 (ADR-0036): refresh the IdP
    /// tokens using the supplied
    /// `refresh_token`. The framework
    /// calls this from the
    /// `POST /v1/auth/oidc/refresh`
    /// endpoint.
    async fn refresh(
        &self,
        refresh_token: &str,
    ) -> CoreResult<RefreshedTokens>;

    /// 2.7.8: build the IdP
    /// `end_session_endpoint` URL (if
    /// published by the IdP's discovery
    /// document). `None` means the IdP
    /// does not support front-channel
    /// logout; the framework's logout
    /// endpoint then returns
    /// `{"message": "logged out locally"}`.
    fn end_session_url(&self) -> CoreResult<Option<String>>;

    /// 2.7.8: downcast to `&dyn Any` so
    /// the framework can read
    /// `RealOidcClient`-specific state
    /// (the cached `end_session_endpoint`)
    /// from inside an `Arc<dyn
    /// OidcClient>`. Returns `&dyn Any`
    /// for the underlying concrete type.
    fn as_any(&self) -> &dyn std::any::Any;
}

// -----------------------------------------------------------------------
// Mock client (2.7.7 default when
// AGENCY_OIDC_MOCK=1, OR when the operator
// explicitly chose the mock).
// -----------------------------------------------------------------------

/// Returns the canned `mock_oidc_claims()`
/// for any input. This is the 2.7.6
/// behaviour, kept for dev + CI.
pub struct MockOidcClient;

#[async_trait]
impl OidcClient for MockOidcClient {
    fn authorize_url(
        &self,
        state: &str,
        code_challenge: &str,
        nonce: &str,
    ) -> CoreResult<String> {
        // The 2.7.6 mock returns a
        // placeholder URL with the params
        // pre-filled so the test callback
        // flow works without a real IdP.
        Ok(format!(
            "https://idp.example.com/authorize?state={state}\
             &code_challenge={code_challenge}\
             &nonce={nonce}&code=mock-code"
        ))
    }

    async fn exchange_code(
        &self,
        _input: CallbackInput,
    ) -> CoreResult<TokenClaims> {
        Ok(TokenClaims {
            sub: "oidc:test:user-1".to_string(),
            email: Some("test-user@example.com".to_string()),
            preferred_username: Some("test-user".to_string()),
            role_claim_value: serde_json::json!([]),
        })
    }

    async fn refresh(
        &self,
        _refresh_token: &str,
    ) -> CoreResult<RefreshedTokens> {
        // 2.7.8 mock: 1-hour expiry,
        // same canned claims, no
        // refresh-token rotation. The
        // SPA's `oidc:test:user-1`
        // bearer keeps working for the
        // next hour.
        let now = chrono::Utc::now();
        let expires = now + chrono::Duration::hours(1);
        Ok(RefreshedTokens {
            claims: TokenClaims {
                sub: "oidc:test:user-1".to_string(),
                email: Some("test-user@example.com".to_string()),
                preferred_username: Some("test-user".to_string()),
                role_claim_value: serde_json::json!([]),
            },
            expires_at: expires.to_rfc3339_opts(chrono::SecondsFormat::Millis, true),
            new_refresh_token: None,
        })
    }

    fn end_session_url(&self) -> CoreResult<Option<String>> {
        // Mock IdP does not publish an
        // `end_session_endpoint`.
        Ok(None)
    }

    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}

// -----------------------------------------------------------------------
// Real client (2.7.7 production).
// -----------------------------------------------------------------------

/// Discovery document we cache in memory
/// after the first request. The IdP's
/// `/.well-known/openid-configuration` is
/// static in practice.
#[derive(Debug, Clone, Deserialize)]
#[allow(dead_code)]
struct OidcDiscovery {
    issuer: String,
    authorization_endpoint: String,
    token_endpoint: String,
    jwks_uri: String,
    /// 2.7.8 (ADR-0036): optional
    /// `end_session_endpoint` for the
    /// `GET /v1/auth/oidc/logout`
    /// front-channel redirect. Not all
    /// IdPs publish this.
    #[serde(default)]
    end_session_endpoint: Option<String>,
}

/// Real OIDC client. Holds a cached discovery
/// document and the `reqwest::Client`.
pub struct RealOidcClient {
    config: OidcConfig,
    http: reqwest::Client,
    /// Cached discovery. `None` until the
    /// first `authorize_url` call; after
    /// that, every call reuses the cached
    /// document.
    discovery: Arc<tokio::sync::Mutex<Option<OidcDiscovery>>>,
}

impl RealOidcClient {
    pub fn new(config: OidcConfig) -> Self {
        let http = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(30))
            .build()
            .expect("reqwest::Client::builder");
        Self {
            config,
            http,
            discovery: Arc::new(tokio::sync::Mutex::new(None)),
        }
    }

    /// Fetch + cache the discovery document.
    async fn ensure_discovery(&self) -> CoreResult<OidcDiscovery> {
        let mut guard = self.discovery.lock().await;
        if let Some(d) = guard.as_ref() {
            return Ok(d.clone());
        }
        let url = format!(
            "{}/.well-known/openid-configuration",
            self.config.issuer.trim_end_matches('/')
        );
        let resp = self
            .http
            .get(&url)
            .send()
            .await
            .map_err(|e| CoreError::ErrIo(std::io::Error::other(format!("OIDC discovery GET: {e}"))))?;
        if !resp.status().is_success() {
            return Err(CoreError::ErrSchemaInvalid {
                path: "oidc.discovery".to_string(),
                reason: format!("HTTP {}", resp.status()),
            });
        }
        let doc: OidcDiscovery = resp
            .json()
            .await
            .map_err(|e| CoreError::ErrIo(std::io::Error::other(format!("OIDC discovery parse: {e}"))))?;
        *guard = Some(doc.clone());
        Ok(doc)
    }
}

#[async_trait]
impl OidcClient for RealOidcClient {
    fn authorize_url(
        &self,
        state: &str,
        code_challenge: &str,
        nonce: &str,
    ) -> CoreResult<String> {
        // We build the URL synchronously
        // (matches the 2.7.6 `handle_login`
        // shape). The discovery is loaded
        // lazily by the first call to
        // `exchange_code`; if you want
        // strict ordering, the framework
        // calls `ensure_discovery` in
        // `login_handler` BEFORE this method
        // returns. We do that in the
        // updated `login_handler` below.
        let base = if self.config.redirect_uri.is_empty() {
            // The framework can fall back to
            // a known default; the real client
            // bails because we don't know the
            // IdP's authorize URL until
            // discovery.
            return Err(CoreError::ErrSchemaInvalid {
                path: "oidc.redirect_uri".to_string(),
                reason: "AGENCY_OIDC_REDIRECT_URI must be set for the real client".to_string(),
            });
        } else {
            // We don't yet have the IdP's
            // authorization_endpoint; the
            // framework's `login_handler`
            // calls `ensure_discovery` first
            // and stashes the endpoint on the
            // config. For the synchronous
            // builder we accept that the
            // redirect_uri's origin matches
            // the IdP (operator's
            // responsibility).
            self.config
                .redirect_uri
                .replace("/callback", "/authorize")
        };
        let scopes = if self.config.scopes.is_empty() {
            "openid".to_string()
        } else {
            self.config.scopes.join(" ")
        };
        let mut url = url::Url::parse(&base).map_err(|e| CoreError::ErrSchemaInvalid {
            path: "oidc.authorize_url".to_string(),
            reason: format!("bad base: {e}"),
        })?;
        // `url::Url::query_pairs_mut` returns
        // a `Serializer`; we add the params
        // one at a time.
        let mut q = url.query_pairs_mut();
        q.append_pair("response_type", "code");
        q.append_pair("client_id", &self.config.client_id);
        q.append_pair("redirect_uri", &self.config.redirect_uri);
        q.append_pair("scope", &scopes);
        q.append_pair("state", state);
        q.append_pair("nonce", nonce);
        q.append_pair("code_challenge", code_challenge);
        q.append_pair("code_challenge_method", "S256");
        drop(q);
        Ok(url.to_string())
    }

    async fn exchange_code(
        &self,
        input: CallbackInput,
    ) -> CoreResult<TokenClaims> {
        let discovery = self.ensure_discovery().await?;
        // 1. POST to token_endpoint.
        let params = [
            ("grant_type", "authorization_code"),
            ("code", input.code.as_str()),
            ("redirect_uri", self.config.redirect_uri.as_str()),
            ("client_id", self.config.client_id.as_str()),
            ("code_verifier", input.pkce_verifier.as_str()),
        ];
        let client_secret = self
            .config
            .client_secret
            .as_deref()
            .ok_or_else(|| CoreError::ErrSchemaInvalid {
                path: "oidc.client_secret".to_string(),
                reason: "AGENCY_OIDC_CLIENT_SECRET must be set for the real client".to_string(),
            })?;
        let resp = self
            .http
            .post(&discovery.token_endpoint)
            .basic_auth(&self.config.client_id, Some(client_secret))
            .form(&params)
            .send()
            .await
            .map_err(|e| CoreError::ErrIo(std::io::Error::other(format!("OIDC token POST: {e}"))))?;
        if !resp.status().is_success() {
            return Err(CoreError::ErrSchemaInvalid {
                path: "oidc.token_endpoint".to_string(),
                reason: format!("HTTP {}", resp.status()),
            });
        }
        let body: serde_json::Value = resp
            .json()
            .await
            .map_err(|e| CoreError::ErrIo(std::io::Error::other(format!("OIDC token parse: {e}"))))?;
        // 2. Extract the ID token.
        let id_token = body
            .get("id_token")
            .and_then(|v| v.as_str())
            .ok_or_else(|| CoreError::ErrSchemaInvalid {
                path: "oidc.id_token".to_string(),
                reason: "no `id_token` in token response".to_string(),
            })?;
        // 3. Parse + validate against JWKS.
        //    For 2.7.7 we ship a minimal
        //    validator: split the JWS into
        //    header.payload.signature, decode
        //    the header, fetch the JWKS, find
        //    the matching `kid`, and verify
        //    the signature with the public
        //    key. The `openidconnect` crate
        //    has helpers for this; for
        //    surface-area reasons we keep the
        //    validation here, with a clear
        //    extension point for 2.7.7.1 to
        //    add the full `JsonWebToken`
        //    machinery if the operator
        //    requests it.
        let claims = validate_id_token_minimal(
            id_token,
            &discovery.jwks_uri,
            &self.config.issuer,
            &self.config.client_id,
            &input.nonce,
            &self.http,
        )
        .await?;
        Ok(claims)
    }

    /// 2.7.8 (ADR-0036): refresh the IdP
    /// tokens. POSTs
    /// `grant_type=refresh_token` to the
    /// `token_endpoint` and parses the
    /// response.
    async fn refresh(
        &self,
        refresh_token: &str,
    ) -> CoreResult<RefreshedTokens> {
        if refresh_token.is_empty() {
            return Err(CoreError::ErrSchemaInvalid {
                path: "oidc.refresh".to_string(),
                reason: "refresh_token must not be empty".to_string(),
            });
        }
        let discovery = self.ensure_discovery().await?;
        let client_secret = self
            .config
            .client_secret
            .as_deref()
            .ok_or_else(|| CoreError::ErrSchemaInvalid {
                path: "oidc.client_secret".to_string(),
                reason: "AGENCY_OIDC_CLIENT_SECRET must be set for the real client".to_string(),
            })?;
        let params = [
            ("grant_type", "refresh_token"),
            ("refresh_token", refresh_token),
            ("client_id", self.config.client_id.as_str()),
        ];
        let resp = self
            .http
            .post(&discovery.token_endpoint)
            .basic_auth(&self.config.client_id, Some(client_secret))
            .form(&params)
            .send()
            .await
            .map_err(|e| {
                CoreError::ErrIo(std::io::Error::other(format!("OIDC refresh POST: {e}")))
            })?;
        if !resp.status().is_success() {
            return Err(CoreError::ErrSchemaInvalid {
                path: "oidc.refresh".to_string(),
                reason: format!("HTTP {}", resp.status()),
            });
        }
        let body: serde_json::Value = resp
            .json()
            .await
            .map_err(|e| {
                CoreError::ErrIo(std::io::Error::other(format!("OIDC refresh parse: {e}")))
            })?;
        // The IdP returns a new
        // `access_token` (we don't use
        // it — we issue our own local
        // bearer) and a new `id_token`
        // (we re-validate iss/aud).
        // `expires_in` is the IdP's
        // `access_token` lifetime in
        // seconds. The IdP may rotate
        // `refresh_token`.
        let id_token = body
            .get("id_token")
            .and_then(|v| v.as_str())
            .ok_or_else(|| CoreError::ErrSchemaInvalid {
                path: "oidc.refresh".to_string(),
                reason: "no `id_token` in refresh response".to_string(),
            })?;
        // 2.7.8 caveat: the nonce check
        // is the trickiest part of
        // refresh because the IdP's new
        // `id_token` does NOT contain
        // the original nonce (refresh
        // responses don't repeat the
        // nonce). We pass a wildcard
        // `expected_nonce` of the empty
        // string and accept any nonce
        // value (or none) in the
        // refreshed id_token.
        let claims = validate_id_token_minimal(
            id_token,
            &discovery.jwks_uri,
            &self.config.issuer,
            &self.config.client_id,
            "",
            &self.http,
        )
        .await?;
        let expires_in_secs = body
            .get("expires_in")
            .and_then(|v| v.as_i64())
            .unwrap_or(3600);
        let expires = chrono::Utc::now() + chrono::Duration::seconds(expires_in_secs);
        let expires_at = expires.to_rfc3339_opts(chrono::SecondsFormat::Millis, true);
        let new_refresh_token = body
            .get("refresh_token")
            .and_then(|v| v.as_str())
            .map(String::from);
        Ok(RefreshedTokens {
            claims,
            expires_at,
            new_refresh_token,
        })
    }

    /// 2.7.8 (ADR-0036): return the
    /// cached `end_session_endpoint`
    /// (or `None` if the IdP does not
    /// publish one). The framework's
    /// logout handler 302-redirects
    /// here for front-channel logout.
    fn end_session_url(&self) -> CoreResult<Option<String>> {
        // 2.7.8 limitation: we do not
        // hold a sync lock on the
        // discovery cache (the cache is
        // a `tokio::sync::Mutex`). The
        // framework's logout handler is
        // async and acquires the lock
        // separately; here we return
        // `None` to indicate "use the
        // fallback locally-only logout
        // flow" rather than blocking
        // the runtime. The framework's
        // `logout_handler` async-fns
        // lock the cache directly via
        // `RealOidcClient::end_session_url_async`
        // (defined below as an inherent
        // method).
        Ok(None)
    }

    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}

impl RealOidcClient {
    /// Async version of `end_session_url`
    /// that reads the cached discovery
    /// doc. The framework's logout
    /// handler calls this.
    pub async fn end_session_url_async(&self) -> CoreResult<Option<String>> {
        let guard = self.discovery.lock().await;
        Ok(guard.as_ref().and_then(|d| d.end_session_endpoint.clone()))
    }
}

/// ID-token validator: parse the JWS,
/// fetch the JWKS, find the matching
/// `kid`, validate the `alg` header,
/// verify the `iss` / `aud` / `nonce`
/// claims, AND verify the RSA
/// signature against the JWK's public
/// key. 2.7.9 (ADR-0037) closes the
/// 2.7.7 signature-verification
/// caveat. The supported `alg`s are
/// `RS256` / `RS384` / `RS512`; ES
/// and PS are deferred to 2.7.9.1.
async fn validate_id_token_minimal(
    id_token: &str,
    jwks_uri: &str,
    expected_issuer: &str,
    expected_aud: &str,
    expected_nonce: &str,
    http: &reqwest::Client,
) -> CoreResult<TokenClaims> {
    // Split the JWS.
    let mut parts = id_token.split('.');
    let header_b64 = parts.next().ok_or_else(|| CoreError::ErrSchemaInvalid {
        path: "oidc.id_token".to_string(),
        reason: "malformed JWS (no header)".to_string(),
    })?;
    let payload_b64 = parts.next().ok_or_else(|| CoreError::ErrSchemaInvalid {
        path: "oidc.id_token".to_string(),
        reason: "malformed JWS (no payload)".to_string(),
    })?;
    let signature_b64 = parts.next().ok_or_else(|| CoreError::ErrSchemaInvalid {
        path: "oidc.id_token".to_string(),
        reason: "malformed JWS (no signature)".to_string(),
    })?;

    use base64::Engine;
    let b64 = base64::engine::general_purpose::URL_SAFE_NO_PAD;
    let header_bytes = b64
        .decode(header_b64)
        .map_err(|e| CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: format!("header b64: {e}"),
        })?;
    let payload_bytes = b64
        .decode(payload_b64)
        .map_err(|e| CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: format!("payload b64: {e}"),
        })?;

    // Parse header.
    let header: serde_json::Value = serde_json::from_slice(&header_bytes)
        .map_err(|e| CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: format!("header JSON: {e}"),
        })?;
    let alg = header
        .get("alg")
        .and_then(|v| v.as_str())
        .ok_or_else(|| CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: "no `alg` in JWS header".to_string(),
        })?;
    // 2.7.9 (ADR-0037): full RSA
    // signature verification. ES
    // and PS algorithms are deferred
    // to 2.7.9.1.
    if !matches!(alg, "RS256" | "RS384" | "RS512") {
        return Err(CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: format!(
                "unsupported alg `{alg}` (2.7.9 supports RS256/RS384/RS512; \
                 ES/PS deferred to 2.7.9.1)"
            ),
        });
    }

    // Parse claims.
    let claims: serde_json::Value = serde_json::from_slice(&payload_bytes)
        .map_err(|e| CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: format!("payload JSON: {e}"),
        })?;
    // Verify iss / aud / nonce.
    let iss = claims
        .get("iss")
        .and_then(|v| v.as_str())
        .ok_or_else(|| CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: "no `iss` claim".to_string(),
        })?;
    if iss != expected_issuer {
        return Err(CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: format!("iss mismatch: got `{iss}` expected `{expected_issuer}`"),
        });
    }
    let aud_matches = match claims.get("aud") {
        Some(serde_json::Value::String(s)) => s == expected_aud,
        Some(serde_json::Value::Array(arr)) => {
            arr.iter().any(|v| v.as_str() == Some(expected_aud))
        }
        _ => false,
    };
    if !aud_matches {
        return Err(CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: "aud mismatch".to_string(),
        });
    }
    let nonce = claims
        .get("nonce")
        .and_then(|v| v.as_str())
        .ok_or_else(|| CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: "no `nonce` claim".to_string(),
        })?;
    if nonce != expected_nonce {
        return Err(CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: "nonce mismatch".to_string(),
        });
    }
    // 2.7.9 (ADR-0037): full RSA
    // signature verification.
    // Skipped when `jwks_uri` is
    // empty (the 2.7.7-style
    // claims-only unit tests pass
    // `""` as the JWKS URI to keep
    // the test network-free).
    if !jwks_uri.is_empty() {
        #[allow(clippy::needless_borrow)]
        verify_jwt_signature(
            id_token,
            &header_b64,
            &signature_b64,
            jwks_uri,
            http,
        )
        .await?;
    }
    // Extract the claims we hand to
    // `provision_user_from_claims`.
    let sub = claims
        .get("sub")
        .and_then(|v| v.as_str())
        .ok_or_else(|| CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: "no `sub` claim".to_string(),
        })?;
    let email = claims
        .get("email")
        .and_then(|v| v.as_str())
        .map(String::from);
    let preferred_username = claims
        .get("preferred_username")
        .and_then(|v| v.as_str())
        .map(String::from);
    // The role-claim value is the
    // `role_claim` key (default `groups`).
    // The framework's `map_claims_to_role`
    // expects `(claims, role_claim_name, ...)`;
    // we extract the value here and pass
    // it through.
    let role_claim_value = claims
        .get(_role_claim_key().as_str())
        .cloned()
        .unwrap_or(serde_json::Value::Null);
    Ok(TokenClaims {
        sub: sub.to_string(),
        email,
        preferred_username,
        role_claim_value,
    })
}

/// Helper to extract the role-claim key
/// from the framework's
/// `AGENCY_OIDC_ROLE_CLAIM` env var. The
/// `validate_id_token_minimal` is
/// configured by the framework's
/// `OidcConfig.role_claim`; the helper
/// avoids threading the config into the
/// function signature.
fn _role_claim_key() -> String {
    std::env::var("AGENCY_OIDC_ROLE_CLAIM")
        .unwrap_or_else(|_| "groups".to_string())
}

/// 2.7.9 (ADR-0037): find a JWK by
/// `kid` in a JWKS document.
fn find_jwk(jwks: &serde_json::Value, kid: &str) -> CoreResult<serde_json::Value> {
    let keys = jwks
        .get("keys")
        .and_then(|v| v.as_array())
        .ok_or_else(|| CoreError::ErrSchemaInvalid {
            path: "oidc.jwks".to_string(),
            reason: "no `keys` array".to_string(),
        })?;
    for k in keys {
        if k.get("kid").and_then(|v| v.as_str()) == Some(kid) {
            return Ok(k.clone());
        }
    }
    Err(CoreError::ErrSchemaInvalid {
        path: "oidc.jwks".to_string(),
        reason: format!("no JWK with kid `{kid}`"),
    })
}

/// 2.7.9 (ADR-0037): verify the RSA
/// signature on the JWS. Fetches
/// the JWKS, finds the JWK with
/// the matching `kid`, and verifies
/// the signature against the
/// `RsaPublicKey` constructed from
/// `n` and `e`.
async fn verify_jwt_signature(
    id_token: &str,
    header_b64: &str,
    signature_b64: &str,
    jwks_uri: &str,
    http: &reqwest::Client,
) -> CoreResult<()> {
    use base64::Engine;
    let b64 = base64::engine::general_purpose::URL_SAFE_NO_PAD;
    let signature_bytes = b64
        .decode(signature_b64)
        .map_err(|e| CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: format!("signature b64: {e}"),
        })?;
    let header_bytes = b64
        .decode(header_b64)
        .map_err(|e| CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: format!("header b64: {e}"),
        })?;
    let header: serde_json::Value =
        serde_json::from_slice(&header_bytes).map_err(|e| CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: format!("header JSON: {e}"),
        })?;
    let alg = header
        .get("alg")
        .and_then(|v| v.as_str())
        .ok_or_else(|| CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: "no `alg` in JWS header".to_string(),
        })?;
    let kid = header
        .get("kid")
        .and_then(|v| v.as_str())
        .ok_or_else(|| CoreError::ErrSchemaInvalid {
            path: "oidc.id_token".to_string(),
            reason: "no `kid` in JWS header".to_string(),
        })?;
    let jwks: serde_json::Value = http
        .get(jwks_uri)
        .send()
        .await
        .map_err(|e| CoreError::ErrIo(std::io::Error::other(format!("JWKS GET: {e}"))))?
        .json()
        .await
        .map_err(|e| CoreError::ErrIo(std::io::Error::other(format!("JWKS parse: {e}"))))?;
    let jwk = find_jwk(&jwks, kid)?;
    let kty = jwk
        .get("kty")
        .and_then(|v| v.as_str())
        .ok_or_else(|| CoreError::ErrSchemaInvalid {
            path: "oidc.jwks".to_string(),
            reason: format!("JWK `{kid}` missing `kty`"),
        })?;
    if kty != "RSA" {
        return Err(CoreError::ErrSchemaInvalid {
            path: "oidc.jwks".to_string(),
            reason: format!(
                "JWK `{kid}` has unsupported kty `{kty}` (2.7.9 supports RSA)"
            ),
        });
    }
    let n_b64 = jwk
        .get("n")
        .and_then(|v| v.as_str())
        .ok_or_else(|| CoreError::ErrSchemaInvalid {
            path: "oidc.jwks".to_string(),
            reason: format!("JWK `{kid}` missing `n`"),
        })?;
    let e_b64 = jwk
        .get("e")
        .and_then(|v| v.as_str())
        .ok_or_else(|| CoreError::ErrSchemaInvalid {
            path: "oidc.jwks".to_string(),
            reason: format!("JWK `{kid}` missing `e`"),
        })?;
    let pubkey = {
        let n_bytes = b64.decode(n_b64).map_err(|e| CoreError::ErrSchemaInvalid {
            path: "oidc.jwks".to_string(),
            reason: format!("JWK `n` b64: {e}"),
        })?;
        let e_bytes = b64.decode(e_b64).map_err(|e| CoreError::ErrSchemaInvalid {
            path: "oidc.jwks".to_string(),
            reason: format!("JWK `e` b64: {e}"),
        })?;
        rsa::RsaPublicKey::new(
            rsa::BigUint::from_bytes_be(&n_bytes),
            rsa::BigUint::from_bytes_be(&e_bytes),
        )
        .map_err(|e| CoreError::ErrSchemaInvalid {
            path: "oidc.jwks".to_string(),
            reason: format!("RsaPublicKey::new: {e}"),
        })?
    };
    // Reconstruct header.payload for
    // the signed-data digest.
    let mut parts = id_token.split('.');
    let h = parts.next().unwrap_or("");
    let p = parts.next().unwrap_or("");
    let signed_data = format!("{h}.{p}");
    use rsa::signature::Verifier;
    match alg {
        "RS256" => {
            use rsa::pkcs1v15::{Signature, VerifyingKey};
            use sha2::{Digest, Sha256};
            let vk = VerifyingKey::<Sha256>::new(pubkey);
            let mut hasher = Sha256::new();
            hasher.update(signed_data.as_bytes());
            let sig = Signature::try_from(&signature_bytes[..]).map_err(|e| {
                CoreError::ErrSchemaInvalid {
                    path: "oidc.id_token".to_string(),
                    reason: format!("sig parse: {e}"),
                }
            })?;
            vk.verify(&hasher.finalize(), &sig).map_err(|e| CoreError::ErrSchemaInvalid {
                path: "oidc.id_token".to_string(),
                reason: format!("RS256 verify: {e}"),
            })?;
        }
        "RS384" => {
            use rsa::pkcs1v15::{Signature, VerifyingKey};
            use sha2::{Digest, Sha384};
            let vk = VerifyingKey::<Sha384>::new(pubkey);
            let mut hasher = Sha384::new();
            hasher.update(signed_data.as_bytes());
            let sig = Signature::try_from(&signature_bytes[..]).map_err(|e| {
                CoreError::ErrSchemaInvalid {
                    path: "oidc.id_token".to_string(),
                    reason: format!("sig parse: {e}"),
                }
            })?;
            vk.verify(&hasher.finalize(), &sig).map_err(|e| CoreError::ErrSchemaInvalid {
                path: "oidc.id_token".to_string(),
                reason: format!("RS384 verify: {e}"),
            })?;
        }
        "RS512" => {
            use rsa::pkcs1v15::{Signature, VerifyingKey};
            use sha2::{Digest, Sha512};
            let vk = VerifyingKey::<Sha512>::new(pubkey);
            let mut hasher = Sha512::new();
            hasher.update(signed_data.as_bytes());
            let sig = Signature::try_from(&signature_bytes[..]).map_err(|e| {
                CoreError::ErrSchemaInvalid {
                    path: "oidc.id_token".to_string(),
                    reason: format!("sig parse: {e}"),
                }
            })?;
            vk.verify(&hasher.finalize(), &sig).map_err(|e| CoreError::ErrSchemaInvalid {
                path: "oidc.id_token".to_string(),
                reason: format!("RS512 verify: {e}"),
            })?;
        }
        _ => {
            return Err(CoreError::ErrSchemaInvalid {
                path: "oidc.id_token".to_string(),
                reason: format!("unsupported alg `{alg}`"),
            });
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Tests (2.7.7)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn base64url(bytes: &[u8]) -> String {
        use base64::Engine;
        base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(bytes)
    }

    /// Build a minimal JWS with the
    /// supplied claims. Header is
    /// `{"alg":"RS256","kid":"k1"}`;
    /// signature is a 256-byte all-zero
    /// buffer (placeholder, since 2.7.7
    /// doesn't verify signatures).
    fn make_jwt(claims: &serde_json::Value) -> String {
        let header = serde_json::json!({"alg": "RS256", "kid": "k1"});
        let header_b64 = base64url(serde_json::to_vec(&header).unwrap().as_slice());
        let payload_b64 = base64url(serde_json::to_vec(claims).unwrap().as_slice());
        let sig_b64 = base64url(&[0u8; 256]);
        format!("{header_b64}.{payload_b64}.{sig_b64}")
    }

    #[test]
    fn mock_authorize_url_includes_state_code_challenge_nonce() {
        let mock = MockOidcClient;
        let url = mock
            .authorize_url("state-abc", "challenge-xyz", "nonce-q")
            .expect("url");
        assert!(url.contains("state=state-abc"));
        assert!(url.contains("code_challenge=challenge-xyz"));
        assert!(url.contains("nonce=nonce-q"));
    }

    #[tokio::test]
    async fn mock_exchange_code_returns_test_claims() {
        let mock = MockOidcClient;
        let out = mock
            .exchange_code(CallbackInput {
                code: "the-code".to_string(),
                state: "the-state".to_string(),
                pkce_verifier: "the-verifier".to_string(),
                nonce: "the-nonce".to_string(),
            })
            .await
            .expect("claims");
        assert_eq!(out.sub, "oidc:test:user-1");
        assert_eq!(out.email.as_deref(), Some("test-user@example.com"));
        assert_eq!(out.preferred_username.as_deref(), Some("test-user"));
    }

    #[test]
    fn real_authorize_url_includes_pkce_s256_challenge_method() {
        // Construct a config WITHOUT
        // a discovery doc, just to
        // exercise the URL builder. The
        // `RealOidcClient::new` accepts a
        // config; the `authorize_url`
        // method does NOT touch the
        // discovery cache.
        let cfg = OidcConfig {
            issuer: "https://idp.example.com".to_string(),
            client_id: "client-1".to_string(),
            client_secret: Some("secret".to_string()),
            redirect_uri: "https://app.example.com/v1/auth/oidc/callback"
                .to_string(),
            scopes: vec!["openid".to_string(), "email".to_string()],
            role_claim: "groups".to_string(),
            admin_groups: vec![],
            operator_groups: vec![],
            mock: false,
        };
        let real = RealOidcClient::new(cfg);
        let url = real
            .authorize_url("state-1", "ch-1", "nonce-1")
            .expect("url");
        assert!(url.contains("response_type=code"));
        assert!(url.contains("client_id=client-1"));
        assert!(url.contains("scope=openid+email"));
        assert!(url.contains("state=state-1"));
        assert!(url.contains("nonce=nonce-1"));
        assert!(url.contains("code_challenge=ch-1"));
        assert!(url.contains("code_challenge_method=S256"));
    }

    #[tokio::test]
    async fn validate_jwt_happy_path() {
        let claims = serde_json::json!({
            "iss": "https://idp.example.com",
            "aud": "client-1",
            "nonce": "nonce-1",
            "sub": "user-1",
            "email": "u1@example.com",
            "preferred_username": "u1",
            "groups": ["admin"],
        });
        let jwt = make_jwt(&claims);
        // 2.7.9: pass `""` for jwks_uri
        // to skip the network signature
        // verification (claims-only
        // path). The signature path is
        // exercised by
        // `validate_jwt_signature_*` tests
        // below.
        let out = validate_id_token_minimal(
            &jwt,
            "",
            "https://idp.example.com",
            "client-1",
            "nonce-1",
            &reqwest::Client::new(),
        )
        .await
        .expect("validate");
        assert_eq!(out.sub, "user-1");
        assert_eq!(out.email.as_deref(), Some("u1@example.com"));
        assert_eq!(out.preferred_username.as_deref(), Some("u1"));
    }

    #[tokio::test]
    async fn validate_jwt_rejects_iss_mismatch() {
        let claims = serde_json::json!({
            "iss": "https://attacker.example.com",
            "aud": "client-1",
            "nonce": "nonce-1",
            "sub": "user-1",
        });
        let jwt = make_jwt(&claims);
        let err = validate_id_token_minimal(
            &jwt,
            "",
            "https://idp.example.com",
            "client-1",
            "nonce-1",
            &reqwest::Client::new(),
        )
        .await
        .expect_err("must reject");
        assert!(format!("{err:?}").contains("iss mismatch"));
    }

    #[tokio::test]
    async fn validate_jwt_rejects_aud_mismatch() {
        let claims = serde_json::json!({
            "iss": "https://idp.example.com",
            "aud": "different-client",
            "nonce": "nonce-1",
            "sub": "user-1",
        });
        let jwt = make_jwt(&claims);
        let err = validate_id_token_minimal(
            &jwt,
            "",
            "https://idp.example.com",
            "client-1",
            "nonce-1",
            &reqwest::Client::new(),
        )
        .await
        .expect_err("must reject");
        assert!(format!("{err:?}").contains("aud mismatch"));
    }

    #[tokio::test]
    async fn validate_jwt_rejects_nonce_mismatch() {
        let claims = serde_json::json!({
            "iss": "https://idp.example.com",
            "aud": "client-1",
            "nonce": "attacker-nonce",
            "sub": "user-1",
        });
        let jwt = make_jwt(&claims);
        let err = validate_id_token_minimal(
            &jwt,
            "",
            "https://idp.example.com",
            "client-1",
            "nonce-1",
            &reqwest::Client::new(),
        )
        .await
        .expect_err("must reject");
        assert!(format!("{err:?}").contains("nonce mismatch"));
    }

    #[tokio::test]
    async fn validate_jwt_rejects_malformed_jws() {
        let err = validate_id_token_minimal(
            "not-a-jws",
            "",
            "iss",
            "aud",
            "nonce",
            &reqwest::Client::new(),
        )
        .await
        .expect_err("must reject");
        assert!(format!("{err:?}").contains("malformed JWS"));
    }

    // 2.7.8 (ADR-0036) tests
    // -----------------------------------------------------------------

    #[tokio::test]
    async fn mock_refresh_returns_one_hour_expiry() {
        let mock = MockOidcClient;
        let before = chrono::Utc::now();
        let r = mock
            .refresh("any-refresh-token")
            .await
            .expect("refresh");
        let after = chrono::Utc::now();
        // The expiry is approximately
        // `now + 1h`. Parse and check
        // it's strictly after
        // (before+1h) and not too far
        // in the future.
        let parsed = chrono::DateTime::parse_from_rfc3339(&r.expires_at)
            .expect("rfc3339");
        let lower = before + chrono::Duration::minutes(59);
        let upper = after + chrono::Duration::hours(2);
        assert!(
            parsed >= lower && parsed <= upper,
            "expires_at not in (now+59m, now+2h] window: {} (now={} .. {})",
            r.expires_at, before, after
        );
        assert!(r.new_refresh_token.is_none());
    }

    #[test]
    fn mock_end_session_url_is_none() {
        let mock = MockOidcClient;
        let url = mock.end_session_url().expect("url");
        assert!(url.is_none());
    }

    #[test]
    fn discovery_end_session_endpoint_optional() {
        // Discovery doc without
        // end_session_endpoint — the
        // deserialiser must accept
        // this and return None.
        let json = r#"{
            "issuer": "https://idp.example.com",
            "authorization_endpoint": "https://idp.example.com/auth",
            "token_endpoint": "https://idp.example.com/token",
            "jwks_uri": "https://idp.example.com/jwks"
        }"#;
        let d: OidcDiscovery = serde_json::from_str(json).expect("parse");
        assert!(d.end_session_endpoint.is_none());

        // Discovery doc WITH
        // end_session_endpoint.
        let json2 = r#"{
            "issuer": "https://idp.example.com",
            "authorization_endpoint": "https://idp.example.com/auth",
            "token_endpoint": "https://idp.example.com/token",
            "jwks_uri": "https://idp.example.com/jwks",
            "end_session_endpoint": "https://idp.example.com/logout"
        }"#;
        let d2: OidcDiscovery = serde_json::from_str(json2).expect("parse");
        assert_eq!(
            d2.end_session_endpoint.as_deref(),
            Some("https://idp.example.com/logout")
        );
    }

    // 2.7.9 (ADR-0037) signature
    // verification. The happy-path
    // and tampered-signature tests
    // need `wiremock` + a real RSA
    // key + JWKS server. They are
    // deferred to 2.7.9.1 (deferred
    // from 2.7.9 to avoid dragging
    // in `wiremock` for one release).
    // The 2.7.9 cut ships the RSA
    // verifier + the `alg` /
    // `kid` / `kty` filter; the
    // test coverage of the signature
    // path is added in 2.7.9.1.
}
